'use strict';
process.env.TZ='Asia/Seoul';
// Generated HTML and assets are outputs. Edit src/ and data/, then run node build.js.
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const root=__dirname;
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const json=p=>JSON.parse(read(p));
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);};
const routes=json('src/data/routes.json'),site=json('src/data/site.json');
const {esc}=require('./src/shared/common');
// Small local CommonJS bundler: build-time only, no npm or browser dependency.
function bundle(entry){
 const modules=new Map();
 function visit(file){
  if(modules.has(file))return file;
  modules.set(file,'');
  let source=read(file);
  if(file.endsWith('.json'))source='module.exports='+JSON.stringify(JSON.parse(source))+';';
  else source=source.replace(/require\(['"]([^'"]+)['"]\)/g,(_,ref)=>{
   if(!ref.startsWith('.'))throw new Error('Only local modules are supported: '+ref);
   let dep=path.posix.normalize(path.posix.join(path.posix.dirname(file),ref));
   if(!path.posix.extname(dep))dep+='.js';
   if(dep.startsWith('../'))throw new Error('Module outside project');
   visit(dep);return '__require('+JSON.stringify(dep)+')';
  });
  modules.set(file,source);return file;
 }
 visit(entry);
 return `(function(){'use strict';const modules={\n${[...modules].map(([id,s])=>JSON.stringify(id)+':function(module,exports,__require){\n'+s+'\n}').join(',\n')}\n};const cache={};function __require(id){if(cache[id])return cache[id].exports;const m=cache[id]={exports:{}};modules[id](m,m.exports,__require);return m.exports;}__require(${JSON.stringify(entry)});})();\n`;
}
const assets=[];
function asset(name,ext,source){const hash=crypto.createHash('sha256').update(source).digest('hex').slice(0,12);const p=`assets/${name}.${hash}.${ext}`;write(p,source);assets.push(p);return '/'+p;}
const siteCss=asset('site','css',read('src/styles/site.css'));
const quizCss=asset('lyric-quiz','css',read('src/styles/lyric-quiz.css'));
const siteJs=asset('site','js',bundle('src/client/site.js'));
const quizJs=asset('lyric-quiz','js',bundle('src/client/lyric-quiz.js'));
const photosRaw=json('data/photos.json');
const photos=(Array.isArray(photosRaw)?photosRaw:photosRaw.photos||[]).filter(x=>x&&x.hidden!==true).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||Number(a.order||999)-Number(b.order||999));
const template=read('src/template.html');
const files=[];
for(const route of routes){
 const key=route.key;
 const render=require('./src/pages/'+(key==='fanchant'?'music':key)+'.js');
 let content;
 if(key==='news')content=render(json('data/news.json'));
 else if(key==='archive')content=render(require('./src/shared/archive-data').mergeArchive(json('data/archive.json')));
 else if(key==='gallery')content=render(photos,new Date(site.snapshotDate));
 else if(key==='today'){let seed=465;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);content=render(new Date(site.snapshotDate),random);}
 else if(key==='music'||key==='fanchant')content=render(route.path);
 else content=render();
 if(!content||content.includes('undefined'))throw new Error('Invalid content for '+key);
 const vars={page:key,title:esc(route.title),description:esc(route.description),canonical:esc(site.origin+route.path),content,siteCss,quizCss,scripts:(key==='quiz'?`<script defer src="${quizJs}"></script>\n`:'')+`<script defer src="${siteJs}"></script>`};
 const output=template.replace(/\{\{(\w+)\}\}/g,(_,key)=>{if(!(key in vars))throw new Error('Unknown template key '+key);return vars[key];});
 const file=route.path.slice(1)+'index.html';write(file,'<!-- Generated by node build.js. DO NOT EDIT. -->\n'+output);files.push(file);
}
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+routes.map(r=>'  <url><loc>'+esc(site.origin+r.path)+'</loc></url>').join('\n')+'\n</urlset>\n');
// Delete only obsolete assets previously owned by this build, never user assets.
const old=fs.existsSync(path.join(root,'build-manifest.json'))?json('build-manifest.json'):{assets:[]};
for(const p of old.assets||[])if(/^assets\/(site|lyric-quiz)\.[a-f0-9]{12}\.(js|css)$/.test(p)&&!assets.includes(p)&&fs.existsSync(path.join(root,p)))fs.unlinkSync(path.join(root,p));
write('build-manifest.json',JSON.stringify({version:site.version,baseline:site.baseline,files:[...files,'sitemap.xml'],assets},null,2)+'\n');
console.log(`Built ${routes.length} pages and ${assets.length} cached assets.`);
