'use strict';
const {TYPES,occurrences,filterEvents,timeText,stateText}=require('./calendar-data');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=d=>`${Number(d.slice(5,7))}월 ${Number(d.slice(8,10))}일`;
function upcoming(events,today){return events.filter(e=>e.date>=today&&e.state!=='cancelled').slice(0,3).map(e=>`<a href="/calendar/?month=${e.date.slice(0,7)}&event=${encodeURIComponent(e.id)}"><time>${e.date.slice(5).replace('-',' / ')}</time><span>${esc(e.title)}</span></a>`).join('')||'<p>새로운 만남을 기다리고 있어요.</p>';}
function eventCard(e,open=false){return `<details class="cal-event${e.state==='cancelled'?' is-cancelled':''}" id="cal-${esc(e.id)}"${open?' open':''}><summary><time datetime="${e.date}">${dateLabel(e.date)}${e.endDate&&e.endDate!==e.date?`<br>~ ${dateLabel(e.endDate)}`:''}</time><span class="cal-event-copy"><span class="cal-meta">${esc(TYPES[e.type])} · ${esc(e.members.length===3?'씨야':e.members.join(' · '))}</span><strong>${esc(e.title)}</strong><span class="cal-time">${esc(timeText(e))}</span></span><span class="cal-state ${e.state}">${e.annual?'기념일':stateText(e)}</span><span class="cal-expand" aria-hidden="true">＋</span></summary><div class="cal-event-body">${e.venue?`<p><b>장소</b> ${esc(e.venue)}</p>`:''}<p>${esc(e.note).replace(/\n/g,'<br>')}</p>${e.basis==='recording'?'<p class="cal-note">녹화일 기준입니다. 방송일과 다를 수 있어요.</p>':''}<div class="cal-links">${e.recordIds.map(id=>`<a href="/archive/?record=${encodeURIComponent(id)}">아카이브 기록 보기</a>`).join('')}${e.sources.map(s=>`<a href="${esc(s.url)}"${s.url.startsWith('/')?'':' target="_blank" rel="noopener noreferrer"'}>${esc(s.label)}${s.url.startsWith('/')?'':' ↗'}</a>`).join('')}</div>${e.state!=='cancelled'?`<button type="button" class="cal-save cal-js" data-save="${esc(e.id)}" hidden>이 일정 저장 (.ics)</button><p class="cal-note">저장한 사본에는 이후 변경이 자동 반영되지 않아요.</p>`:''}</div></details>`;}
function monthContent(events,state){
 const {month,day='',today='',event=''}=state;
 const list=filterEvents(occurrences(events,month),state).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)||a.title.localeCompare(b.title,'ko'));
 const [year,m]=month.split('-').map(Number),offset=new Date(Date.UTC(year,m-1,1)).getUTCDay(),days=new Date(Date.UTC(year,m,0)).getUTCDate();
 const grid=Array.from({length:offset},()=>'<span class="cal-pad" aria-hidden="true"></span>').concat(Array.from({length:days},(_,i)=>{const d=month+'-'+String(i+1).padStart(2,'0'),entries=list.filter(e=>e.date<=d&&(e.endDate||e.date)>=d);return `<button type="button" data-day="${d}" class="cal-day${d===today?' is-today':''}${d===day?' is-selected':''}" aria-pressed="${d===day}" aria-label="${m}월 ${i+1}일, ${entries.length}개 일정${d===today?', 오늘':''}"><span class="cal-day-num">${i+1}</span>${entries.length?`<span class="cal-dots" aria-hidden="true">${[...new Set(entries.map(e=>e.type))].map(t=>`<i class="dot-${t}"></i>`).join('')}</span><span class="cal-day-preview" aria-hidden="true">${esc(entries[0].title)}</span><small>${entries.length}건</small>`:''}</button>`;})).join('');
 const chosen=day?list.filter(e=>e.date<=day&&(e.endDate||e.date)>=day):list;
 return {grid:`<div class="cal-week" aria-hidden="true">${['일','월','화','수','목','금','토'].map(x=>`<span>${x}</span>`).join('')}</div><div class="cal-grid" aria-label="${year}년 ${m}월">${grid}</div>`,list:chosen.length?chosen.map(e=>eventCard(e,e.id===event)).join(''):`<div class="cal-empty"><strong>${day?dateLabel(day):m+'월'}에${state.member==='all'&&state.type==='all'?'':' 선택한 조건으로'} 등록된 일정이 없어요.</strong><p>일정이 확인되면 이곳에 함께 모아둘게요.</p></div>`,heading:day?dateLabel(day)+'의 일정':m+'월 전체 일정',count:chosen.length,monthCount:list.length};
}
module.exports={esc,eventCard,monthContent,dateLabel,upcoming};
