'use strict';
const {data,esc,grade}=require('./exam');
// Read each physical sheet down the left column, then down the right column.
const sheets=[[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]],[[16,17,18,19],[20,21,22,23,24]]];
function paperHeader(page,name,bank){return `<header class="exam-paper-header"><div class="exam-paper-top"><span>SEEYA ARCHIVE · ${esc(bank.area)} 영역</span><span>${esc(bank.period)} · 난이도 ${esc(bank.level)}</span></div><p class="exam-paper-subtitle">씨야와 함께한 시간에 관한 스물다섯 가지 질문</p><h2>씨야 모의고사</h2><div class="exam-candidate"><div><b>성명</b><span>${name?esc(name):'________________'}</span></div><div><b>문항</b><span>25문항 / 100점</span></div><div><b>시험 시간</b><span>제한 없음</span></div></div><p class="exam-paper-instructions">${page===2?'[17–20] 객관식 · [21–25] 주관식':'알맞은 답을 하나씩 고르세요.'}　모든 문항의 배점은 4점입니다.</p></header>`;}
function papers(renderQuestion,name='',bank=data){return sheets.map((cols,i)=>`<section class="exam-paper" data-compact="${bank.key==='hard'&&i===1}" aria-label="시험지 ${i+1}쪽">${paperHeader(i,name,bank)}<div class="exam-paper-columns">${cols.map(col=>`<div class="exam-paper-column">${col.map(n=>renderQuestion(bank.questions[n],n)).join('')}</div>`).join('')}</div><footer class="exam-paper-footer"><span>SEEYA ARCHIVE</span><span>${i+1} / ${sheets.length}</span><span>${i===2?'수고하셨습니다.':'다음 쪽에 계속됩니다.'}</span></footer></section>`).join('');}
function level(score){return score>=90?1:score>=80?2:score>=60?3:score>=40?4:5;}
function report(answers,name,bank=data){const r=grade(answers,bank),choice=r.rows.slice(0,20).filter(x=>x.correct).length,text=r.count-choice;return `<section class="exam-report" aria-labelledby="reportTitle"><header><div class="exam-paper-top"><span>SEEYA ARCHIVE</span><span>팬메이드 모의고사</span></div><p class="exam-report-subtitle">씨야 모의고사 · 난이도 ${esc(bank.level)}</p><h1 id="reportTitle" tabindex="-1" data-focus>성적 통지서</h1></header><dl class="exam-report-person"><div><dt>응시자</dt><dd>${esc(name||'응시자')}</dd></div><div><dt>시험 영역</dt><dd>${esc(bank.area)}</dd></div><div><dt>총 문항</dt><dd>25문항</dd></div></dl><div class="exam-report-score"><div><span>종합 점수</span><p><strong>${r.score}</strong> / 100점</p></div><div><span>성취 등급</span><p><strong>${level(r.score)}</strong> 등급</p></div></div><table class="exam-report-table"><caption>영역별 성적</caption><thead><tr><th scope="col">영역</th><th scope="col">문항 수</th><th scope="col">정답 수</th><th scope="col">점수</th></tr></thead><tbody><tr><th scope="row">객관식</th><td>20</td><td>${choice}</td><td>${choice*4} / 80</td></tr><tr><th scope="row">주관식</th><td>5</td><td>${text}</td><td>${text*4} / 20</td></tr><tr><th scope="row">합계</th><td>25</td><td>${r.count}</td><td>${r.score} / 100</td></tr></tbody></table><h2 class="exam-mark-title">문항별 정오표</h2><p class="exam-help">정답 ${r.count} · 오답 ${25-r.count-r.blank} · 미응답 ${r.blank}<br>번호를 누르면 해당 문항의 해설로 이동합니다.</p><div class="exam-report-marks">${r.rows.map((row,i)=>`<button type="button" data-review="${row.id}" class="${row.correct?'correct':row.answered?'wrong':'blank'}" aria-label="${i+1}번 ${row.correct?'정답':row.answered?'오답':'미응답'} 해설 보기"><span>${i+1}</span><b>${row.correct?'O':row.answered?'X':'—'}</b></button>`).join('')}</div><p class="exam-report-comment">${r.score>=80?'오래 간직한 씨야의 순간들이 답안에 가득합니다.':r.score>=40?'기억하던 순간과 새로 알게 된 이야기를 함께 간직해주세요.':'오늘 새로 만난 이야기만큼 씨야와 조금 더 가까워졌습니다.'}</p><footer class="exam-report-footer"><span>당신의 마음에 남아 있는 씨야를 응원합니다.<br><b>SEEYA ARCHIVE</b></span><span class="exam-seal" aria-label="씨야 아카이브 기념 도장">씨야<br>기록실</span></footer><p class="exam-grade-guide">등급 기준: 1등급 90점 이상 · 2등급 80점 이상 · 3등급 60점 이상 · 4등급 40점 이상 · 5등급 40점 미만<br>팬게임 자체 기준이며 상대평가가 아닙니다.</p></section><div class="exam-actions exam-result-actions"><button type="button" data-retry>다시 풀기</button><button type="button" class="exam-secondary" data-welcome>영역 선택으로</button><button type="button" class="exam-secondary" data-print>빈 시험지 인쇄 / PDF 저장</button></div>`;}
module.exports={sheets,papers,level,report};
