'use strict';
const P=require('./passport');
function songs(entries){return [...new Set(entries.filter(e=>e.kind==='concert'&&P.completed(e)).flatMap(e=>e.songs||[]))];}
function tourEntries(t,entries){return entries.filter(e=>e.kind==='concert'&&P.completed(e)&&e.date===t.date&&(e.eventId===t.eventId||e.archiveId===t.archiveId));}
function firstSongs(entry,entries){const prior=entries.filter(e=>e.entryId!==entry.entryId&&e.kind==='concert'&&P.completed(e)&&e.date&&entry.date&&(e.date<entry.date||e.date===entry.date&&e.createdAt<entry.createdAt));const heard=new Set(prior.flatMap(e=>e.songs||[]));return (entry.songs||[]).filter(id=>!heard.has(id));}
function summaryText(state){const n=P.summary(state.entries);return `WITH YOU PASSPORT · 공연 ${n.concert}회 · 장소 ${n.visit}회 · 팬 행사 ${n.event}회 · 라이브로 들은 곡 ${songs(state.entries).length}곡`;}
function url(value){if(!value)return '';const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error('링크는 https:// 주소로 입력해 주세요.');return u.href;}
function youtube(value){try{const u=new URL(value),host=u.hostname.replace(/^www\./,'');const id=host==='youtu.be'?u.pathname.slice(1):['youtube.com','m.youtube.com'].includes(host)?(u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([^/]+)/)?.[1]):'';return /^[\w-]{11}$/.test(id||'')?id:'';}catch{return '';}}
function publicSummary(state,nickname=false){const done=state.entries.filter(e=>P.completed(e)).sort((a,b)=>b.date.localeCompare(a.date));return {v:1,n:nickname?state.profile.nickname:'',s:state.profile.since,c:P.summary(done),r:done.slice(0,80).map(e=>({k:e.kind,d:e.date,t:e.title.slice(0,100),i:e.eventId,a:e.archiveId,z:(e.songs||[]).length}))};}
function checkSummary(x){if(!x||x.v!==1||!Array.isArray(x.r)||x.r.length>80)throw Error('올바른 공유 요약이 아닙니다.');const str=(v,n)=>{if(typeof v!=='string'||v.length>n)throw Error('공유 내용이 너무 깁니다.');return v;};const count=v=>{if(!Number.isInteger(v)||v<0||v>2000)throw Error('공유 집계를 확인할 수 없습니다.');return v;};return {v:1,n:str(x.n,30),s:P.profile({since:str(x.s,10)}).since,c:Object.fromEntries(Object.keys(P.KINDS).map(k=>[k,count(x.c?.[k])])),r:x.r.map(r=>({k:Object.hasOwn(P.KINDS,r.k)?r.k:(()=>{throw Error('기록 종류 오류');})(),d:P.date(str(r.d,10)),t:str(r.t,100),i:str(r.i,160),a:str(r.a,160),z:count(r.z)}))};}
module.exports={songs,tourEntries,firstSongs,summaryText,url,youtube,publicSummary,checkSummary};
