'use strict';
const {MEMBERS,TYPES}=require('../shared/calendar-data');
const {esc,monthContent,eventCard}=require('../shared/calendar-view');
module.exports=function calendar(data){
 const month=data.asOf.slice(0,7),view=monthContent([...data.events,...data.anniversaries],{month,day:data.asOf,today:data.asOf,member:'all',type:'all'}),next=data.events.filter(e=>e.date>=data.asOf&&e.state!=='cancelled').slice(0,3);
 return `<div class="page calendar-page"><header class="cal-hero"><div class="eye">OUR NEXT MOMENT</div><h1>CALENDAR</h1><p>씨야를 만나는 날, 함께 기억할 날.<br>공연부터 방송, 소중한 기념일까지 한눈에 살펴보세요.</p><a class="cal-subscribe" href="/calendar/#calendarSubscribe">씨야 일정 구독</a></header>
 <section class="cal-upcoming" aria-labelledby="calUpcomingTitle"><h2 id="calUpcomingTitle">다가오는 만남</h2><div>${next.map(e=>`<a href="/calendar/?month=${e.date.slice(0,7)}&event=${encodeURIComponent(e.id)}"><time>${e.date.slice(5).replace('-',' / ')}</time><span>${esc(e.title)}</span></a>`).join('')||'<p>새로운 만남을 기다리고 있어요.</p>'}</div></section>
 <section class="cal-workspace" aria-label="일정 찾아보기"><form id="calendarFilters" class="cal-filters"><label>멤버<select name="member"><option value="all">전체</option><option value="group">씨야 전체</option>${MEMBERS.map(m=>`<option>${m}</option>`).join('')}</select></label><label>분류<select name="type"><option value="all">전체 일정</option>${Object.entries(TYPES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label class="cal-check"><input type="checkbox" name="anniversaries" checked> 기념일 함께 보기</label><span>한국 시간 (KST)</span></form>
 <div class="cal-toolbar"><div><button type="button" data-month-step="-1" aria-label="이전 달">‹</button><label class="cal-month-label"><span class="cal-sr">연월 선택</span><input id="calendarMonth" type="month" value="${month}" min="2006-01" max="2100-12"></label><button type="button" data-month-step="1" aria-label="다음 달">›</button></div><button type="button" id="calendarToday">오늘</button><div class="cal-view-switch" aria-label="보기 방식"><button type="button" data-view="calendar" aria-pressed="true">달력</button><button type="button" data-view="list" aria-pressed="false">목록</button></div></div>
 <p id="calendarStatus" class="cal-status" role="status">${Number(month.slice(5))}월 · ${view.monthCount}개 일정 · 선택한 날 ${view.count}개</p><div class="cal-columns"><div id="calendarGrid" class="cal-board">${view.grid}<div class="cal-legend">${Object.entries(TYPES).map(([k,v])=>`<span data-type="${k}"><i class="dot-${k}" aria-hidden="true"></i>${v}</span>`).join('')}</div><p class="cal-note">날짜를 누르면 그날의 일정을 볼 수 있어요.</p></div><section class="cal-agenda" aria-labelledby="calendarListTitle"><div class="cal-list-heading"><h2 id="calendarListTitle">${view.heading}</h2><button type="button" id="calendarAllDays">이번 달 전체</button></div><div id="calendarList">${view.list}</div></section></div>
 <noscript><p>빌드 시점의 ${data.asOf} 일정입니다. 다른 달 탐색·필터·개별 일정 저장은 JavaScript를 켜면 이용할 수 있어요. 아래 구독 주소는 그대로 이용할 수 있습니다.</p></noscript></section>
 <section id="calendarSubscribe" class="cal-subscription" aria-labelledby="calSubscribeTitle"><div class="eye">KEEP OUR DATES</div><h2 id="calSubscribeTitle">내 캘린더에서도 만나요</h2><p>활동 일정과 기념일 중 원하는 달력을 구독하세요.<br>구독 달력은 변경 사항을 가져오며, 파일을 가져와 저장한 사본은 자동으로 바뀌지 않아요.</p><div class="cal-feed-grid">${[['activities','활동 일정','날짜가 확인된 공연·방송·발매·예매 일정'],['anniversaries','기념일','멤버 생일·씨야 데뷔일·앨범 발매 기념일']].map(([id,title,desc])=>`<article><h3>${title}</h3><p>${desc}</p><label>${title} 구독 주소<input readonly value="https://seeya-fanpage.com/calendar/${id}.ics" aria-label="${title} 구독 주소"></label><div class="cal-feed-actions"><button type="button" data-copy="${id}" class="cal-js" hidden>주소 복사</button><a href="/calendar/${id}.ics" download="seeya-${id}.ics">파일 내려받기</a></div></article>`).join('')}</div><p id="calendarCopyStatus" role="status"></p><details class="cal-help"><summary>Google 캘린더에 구독하는 방법</summary><ol><li>PC 웹에서 Google 캘린더를 엽니다.</li><li>‘다른 캘린더’ 옆의 ＋ → ‘URL로 추가’를 선택합니다.</li><li>위에서 복사한 구독 주소를 붙여넣고 추가합니다.</li></ol><a href="https://support.google.com/calendar/answer/37100?hl=ko" target="_blank" rel="noopener noreferrer">Google 공식 도움말 ↗</a></details><p class="cal-note">구독 갱신은 캘린더 서비스에 따라 늦어질 수 있어요. 변경·취소 여부는 사이트와 원문 안내를 확인해 주세요.<br>시간 미정 일정은 하루 일정으로 표시합니다. 푸시 알림은 아직 제공하지 않으며, 개인 캘린더의 알림은 해당 앱 설정에 따릅니다.</p></section>
 <p class="cal-footnote">실제 방송일·행사일·발매일이 확인된 아카이브 기록을 연결합니다.<br>날짜 미확정 자료, 게시일만 알려진 영상·기사, 개별 출연일이 정해지지 않은 공연 시즌은 달력에서 제외합니다.</p></div>`;
};
