const {W,esc}=require('../shared/common');
const nav=require('../shared/archive-nav');
const {concerts,concertPath,categoryLabels}=require('../shared/concert-data');
const site=require('../data/site.json');
function ticket(c){return `<div class="concert-ticket concert-theme-${c.theme}"><div class="concert-ticket-top"><span>SEEYA · CONCERT ARCHIVE</span><span>${esc(c.first.slice(0,4))}</span></div><div class="concert-ticket-name">${esc(c.name)}</div><p>${esc(c.subtitle)}</p><div class="concert-ticket-stub"><span>${esc(c.events.map(e=>e.label).join(' · '))}</span><span aria-hidden="true">▥▥▥</span></div></div>`;}
function concertIndex(route,archive){const list=concerts(archive,site.snapshotDate.slice(0,10));const years=[...new Set(list.flatMap(c=>c.years))].sort().reverse();return W(`<section class="concert-heading"><div class="eye">ARCHIVE · LIVE MEMORIES</div><h1>콘서트 기록관</h1><p class="lead">함께 노래했던 날,<br>그 공연의 기억을 다시 펼쳐보세요.</p>${nav('concerts')}</section>
 <section class="concert-intro"><span class="eye">OUR CONCERT COLLECTION</span><h2>한 장의 티켓,<br>오래 남을 우리의 순간.</h2><p>THE FAN부터 첫 단독 콘서트 女神까지.<br>공연을 선택하고 지역별 일정과 영상, 그날의 기록을 만나보세요.</p><a href="/archive/concerts/the-fan-2026/">THE FAN 기록 펼치기 ↗</a></section>
 <section class="concert-library" data-concert-library><div class="concert-list-heading"><h2>공연 찾아보기</h2><span>${list.length}개 기록관 · ${list.reduce((n,c)=>n+c.events.length,0)}건의 공연·지역 기록</span></div>
 <form class="stage-controls" role="search"><label class="stage-search">공연 검색<input name="q" type="search" placeholder="공연명·멤버·지역으로 검색" autocomplete="off"></label><label>분류<select name="category"><option value="all">전체 공연</option>${Object.entries(categoryLabels).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>연도<select name="year"><option value="all">모든 연도</option>${years.map(y=>`<option value="${y}">${y}년</option>`).join('')}</select></label><label>정렬<select name="sort"><option value="recommended">기록관 순서</option><option value="newest">최신 공연순</option><option value="oldest">오래된 공연순</option></select></label></form>
 <p class="concert-result" role="status" aria-live="polite">${list.length}개 기록관</p><div class="concert-grid">${list.map((c,i)=>`<a class="concert-card" href="${concertPath(c)}" data-concert-card data-order="${i}" data-date="${c.first}" data-last="${c.last}" data-category="${c.category}" data-years="${c.years.join('|')}" data-search="${esc([c.name,c.subtitle,...c.members,...c.events.map(e=>e.label+' '+(e.venue||''))].join(' '))}">${ticket(c)}<div class="concert-card-copy"><small>${categoryLabels[c.category]}${c.events.some(e=>e.state==='upcoming')?' · 예정 일정 포함':''}</small><h3>${esc(c.name)}</h3><p>${esc(c.subtitle)}</p><div><span>지역·공연 기록 ${c.events.length} · 자료 ${c.sourceCount}</span><b aria-hidden="true">↗</b></div></div></a>`).join('')}</div>
 <div class="concert-empty" hidden><h3>조건에 맞는 공연이 없어요.</h3><p>검색어와 연도를 바꿔보세요.</p><button type="button" data-concert-reset>전체 공연 보기</button></div><nav class="concert-pagination" aria-label="공연 목록 페이지" hidden></nav><p class="concert-footnote">단독 콘서트와 팬미팅 기록부터 차례로 모으고 있습니다. 티켓 모양의 카드는 공연 정보를 표현한 디자인입니다.<br>더 많은 공연·행사 기록은 <a href="/archive/">전체 아카이브</a>에서 볼 수 있어요.</p><noscript><p>모든 공연을 표시하고 있습니다. 검색·필터는 JavaScript를 켜면 사용할 수 있습니다.</p></noscript></section>`);}
module.exports=concertIndex;module.exports.ticket=ticket;
