const {W,esc}=require('../shared/common');
const nav=require('../shared/archive-nav');
const {concerts,stateLabels}=require('../shared/concert-data');
const {archiveDateLabel}=require('../shared/views');
const {songByTitle,songPath,videoId}=require('../shared/stage-data');
const site=require('../data/site.json');
const {ticket}=require('./concerts');
function links(items){return items.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label||'원본 자료')} <span aria-hidden="true">↗</span></a>`).join('');}
module.exports=function concertDetail(route,archive){const c=concerts(archive,site.snapshotDate.slice(0,10)).find(c=>c.id===route.concertId);if(!c)throw new Error('Missing concert '+route.concertId);
 const past=c.events.filter(e=>e.state==='past'),initial=past.at(-1)||c.events[0];
 return W(`<section class="concert-heading concert-detail-heading"><div class="eye">ARCHIVE · CONCERT COLLECTION</div>${nav('concerts')}<a class="concert-back" href="/archive/concerts/">← 콘서트 기록관 목록</a><div class="concert-hero">${ticket(c)}<div><span class="eye">${esc(c.first.slice(0,4))} · ${esc(c.subtitle)}</span><h1>${esc(c.name)}</h1><p>${esc(c.description)}</p><span class="concert-hero-count">지역·공연 기록 ${c.events.length} · 연결된 자료 ${c.sourceCount}</span></div></div></section>
 <section class="concert-detail" data-concert-detail data-initial-event="${esc(initial.id)}"><div class="concert-region-heading"><h2>${c.events.length>1?'지역별 기록':'공연 기록'}</h2><p>날짜가 여러 날인 경우 한 기록으로 묶어 표시합니다.</p></div>
 <nav class="concert-region-nav" aria-label="공연 지역 선택">${c.events.map(e=>`<a href="?event=${encodeURIComponent(e.id)}" data-concert-event="${esc(e.id)}"><strong>${esc(e.label)}</strong><span>${esc(e.date.slice(5).replace('-','.'))}${e.endDate?' ~ '+esc(e.endDate.slice(5).replace('-','.')):''}</span><small>${stateLabels[e.state]}</small></a>`).join('')}</nav>
 <nav class="concert-detail-tabs" aria-label="공연 내용 선택"><a href="?event=${encodeURIComponent(initial.id)}&view=record" data-concert-view="record">공연 기록</a><a href="?event=${encodeURIComponent(initial.id)}&view=media" data-concert-view="media">영상·자료</a></nav>
 <p class="concert-selection-status" role="status" aria-live="polite"></p>
 ${c.events.map(e=>`<article data-concert-panel="${esc(e.id)}" data-label="${esc(e.label)}"><div class="concert-session-head"><h2>${esc(e.label)} · ${esc(c.name)}</h2><span class="concert-state concert-state-${e.state}">${stateLabels[e.state]}</span></div><div data-concert-content="record"><dl class="concert-facts"><div><dt>공연 날짜</dt><dd>${archiveDateLabel(e)}</dd></div><div><dt>공연장</dt><dd>${esc(e.venue||'공연장 정보 확인 중')}</dd></div><div><dt>출연 기록</dt><dd>${esc((e.members||[]).join(' · ')||'출연 정보 확인 중')}</dd></div></dl>${e.note?`<section class="concert-memo"><h3>이 공연의 기록</h3><p>${esc(e.note)}</p></section>`:''}<section class="concert-songs"><h3>기록된 곡</h3>${e.songs?.length?`<p>확인된 일부 곡입니다. 전체 세트리스트나 공연 순서를 뜻하지 않습니다.</p><ul>${[...new Set(e.songs)].map(name=>{const s=songByTitle(name);return `<li>${s?`<a href="${songPath(s)}">${esc(name)} <span>곡별 무대 →</span></a>`:`<span>${esc(name)}</span>`}</li>`;}).join('')}</ul>`:`<p>${e.state==='upcoming'?'공연 후 확인된 곡을 이곳에 모을 예정입니다.':'이 공연에서 부른 곡은 아직 정리되지 않았어요.'}</p>`}</section></div>
 <div data-concert-content="media"><section class="concert-media"><h3>공연 영상 <small>${e.videos.length}</small></h3>${e.videos.length?`<div class="concert-video-grid">${e.videos.map(v=>`<a href="${esc(v.url)}" target="_blank" rel="noopener noreferrer"><div class="concert-video-thumb"><span>SEEYA · LIVE</span><img src="https://i.ytimg.com/vi/${videoId(v.url)}/hqdefault.jpg" alt="" loading="lazy" onerror="this.remove()"><b aria-hidden="true">▶</b></div><div class="concert-video-copy"><strong>${esc(v.label||'공연 영상')}</strong>${v.publishedDate?`<small>게시일 ${esc(v.publishedDate)}</small>`:''}<span>원본 영상 보기 ↗</span></div></a>`).join('')}</div><p class="concert-footnote">영상은 원본 게시 페이지에서 열립니다. 여러 날짜의 공연이 묶인 경우 영상별 날짜는 원본 제목과 공연 메모를 함께 확인해주세요.</p>`:'<p class="concert-media-empty">공연 영상이 아직 등록되지 않았어요.</p>'}</section><section class="concert-references"><h3>공연 안내·관련 자료</h3>${e.references.length?links(e.references):'<p>연결된 관련 자료가 아직 없어요.</p>'}</section></div><a class="concert-original" href="/archive/?record=${encodeURIComponent(e.id)}">전체 아카이브에서 이 기록 보기 →</a></article>`).join('')}
 <noscript><p>모든 지역의 공연 정보와 자료를 표시하고 있습니다. 지역 전환은 JavaScript를 켜면 사용할 수 있습니다.</p></noscript></section>`);};
