const resolveLibrary=require('../shared/radio-library');
const {resolveRadio,filterRadio,cards,selection,esc,paginateRadio,pagination}=require('../shared/radio');
module.exports=function(archive,today){
 const rows=resolveLibrary(archive,today),first=rows[0];
 return `<section class="radio-page"><header class="radio-heading"><div class="eye">THE VOICES WE KEEP</div><h1>씨야 라디오</h1><p>일상 곁에 두고 듣는, 세 사람의 목소리</p><span class="radio-preview-label">영상·팟캐스트 ${rows.length}개 · 라디오 모아듣기</span></header>
 <div class="radio-layout"><section class="radio-player-panel" aria-label="선택한 방송">
 <div id="radioMedia" class="${first?.provider==='spotify'?'radio-podcast':'radio-video'}" ${first?'':'hidden'}>${first?.provider==='spotify'?`<iframe src="${esc(first.embed)}" title="${esc(first.title)}" allow="autoplay; encrypted-media; fullscreen; picture-in-picture" loading="eager"></iframe>`:`<iframe id="radioPlayer" ${first?`src="https://www.youtube.com/embed/${first.videoId}?rel=0&amp;enablejsapi=1&amp;playsinline=1"`:''} title="${esc(first?.title||'라디오 영상')}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`}</div>
 <div id="radioCurrent">${first?selection(first):'<h2>준비된 라디오 영상이 없습니다.</h2>'}</div>
 <div id="radioTransport" class="radio-transport"><label class="radio-sr" for="radioSeek">재생 위치</label><input id="radioSeek" type="range" min="0" max="0" value="0" step="1" disabled><div class="radio-times"><span id="radioElapsed">0:00</span><span id="radioDuration">--:--</span></div><div class="radio-main-controls"><button id="radioBack" class="radio-skip" type="button" aria-label="15초 뒤로" disabled>↶<small>15</small></button><button id="radioPlay" class="radio-play" type="button" aria-label="재생" disabled><span aria-hidden="true">▶</span></button><button id="radioForward" class="radio-skip" type="button" aria-label="15초 앞으로" disabled><small>15</small>↷</button></div>
 </div>
 <div class="radio-compact-controls">
  <div class="radio-options"><label><span class="radio-sr">재생 속도</span><select id="radioSpeed" aria-label="재생 속도" disabled><option value="1">1.0×</option></select></label><button id="radioRestart" type="button" disabled>처음부터</button><button id="radioSave" type="button" aria-pressed="false" ${first?'':'disabled'}>♡ 저장</button><button id="radioPodcastReload" type="button" aria-label="플레이어 다시 불러오기" title="플레이어 다시 불러오기" hidden>↻ 새로고침</button></div>
  <div class="radio-common-actions"><button id="radioPreviousManual" type="button" aria-label="이전 목록 듣기" title="이전 목록 듣기" disabled>이전 목록</button><button id="radioNextManual" type="button" aria-label="다음 목록 듣기" title="다음 목록 듣기">다음 목록</button><div class="radio-modes" role="group" aria-label="재생 방식"><button id="radioShuffle" type="button" aria-pressed="false">랜덤 재생</button><button id="radioRepeatOne" type="button" aria-pressed="false">한 편 반복</button></div></div>
 </div><div class="radio-continuous"><label><input id="radioContinuous" type="checkbox"> 연속재생</label><p id="radioNext">현재 목록 순서대로 이어집니다.</p></div>
 <p id="radioSelectionStatus" class="radio-status" role="status">${first?'플레이어 연결 중 · 플레이어 안의 재생 버튼도 사용할 수 있어요.':''}</p>
 <div class="radio-source-links"><a id="radioOriginal" href="${first?.provider==='spotify'?esc(first.url):first?'https://www.youtube.com/watch?v='+first.videoId:'https://www.youtube.com/'}" target="_blank" rel="noopener noreferrer">${first?.provider==='spotify'?'Spotify':'YouTube'}에서 열기 ↗</a><a id="radioArchive" href="${first?'/archive/?record='+encodeURIComponent(first.id):'/archive/'}">아카이브 기록 →</a></div>
 <p class="radio-device-note">화면을 잠그고 편하게 들어보세요.<br>기기와 브라우저에 따라 재생이 멈출 수 있어요.</p>
 </section><section class="radio-library" aria-label="방송 목록"><h2 class="radio-sr">방송 고르기</h2>
 <label class="radio-sr" for="radioSearch">방송·프로그램·출연 멤버 검색</label><div class="radio-search-wrap"><span aria-hidden="true">⌕</span><input id="radioSearch" type="search" placeholder="방송명, 출연 멤버 검색" autocomplete="off"></div>
 <div class="radio-members" role="group" aria-label="출연 멤버">${['전체','씨야','남규리','김연지','이보람'].map(m=>`<button type="button" data-radio-member="${m}" aria-pressed="${m==='전체'}">${m}</button>`).join('')}</div>
 <div class="radio-format"><label for="radioFormat">자료 종류</label><select id="radioFormat"><option value="all">전체</option><option value="video">유튜브 영상</option><option value="podcast">팟캐스트</option></select></div><div class="radio-list-toolbar"><label class="radio-saved-filter"><input id="radioSavedOnly" type="checkbox"> 저장한 방송만</label><span id="radioCount" role="status">총 ${rows.length}개 · 1 / ${paginateRadio(rows).total} 페이지</span><select id="radioSort" aria-label="정렬"><option value="newest">최신순</option><option value="oldest">오래된순</option></select></div>
 <div id="radioList">${cards(paginateRadio(rows).items,first?.id)}</div><nav id="radioPagination" class="radio-pagination" aria-label="라디오 목록 페이지">${pagination(1,paginateRadio(rows).total)}</nav><p class="radio-filter-note">‘씨야’는 세 멤버가 함께한 기록을 모읍니다.<br>날짜는 방송일을 우선하며, 미확인 자료는 영상 게시일 또는 잠정 방송일로 구분합니다.</p><noscript><p>검색과 방송 전환에는 JavaScript가 필요합니다. 영상의 기본 조작 버튼은 그대로 사용할 수 있습니다.</p></noscript>
 </section></div>
 <div class="radio-bottom" aria-label="현재 방송 요약"><span class="radio-bottom-icon" aria-hidden="true">ıllı</span><div><strong id="radioBottomTitle">${esc(first?.title||'씨야 라디오')}</strong><span id="radioBottomStatus">한 편씩, 천천히</span></div><button id="radioToPlayer" type="button">플레이어로 ↑</button></div>
 <details class="radio-test"><summary>재생 안내</summary><p>삼성 인터넷에서 잠글 때 멈춘다면 설정 → 유용한 기능 → 백그라운드 재생을 확인해 주세요. YouTube·Spotify 공식 플레이어를 유지하고 같은 재생·일시정지·15초 이동 버튼을 연결했습니다. 팟캐스트 속도 조절은 Spotify 플레이어 안에서 이용할 수 있습니다. 잠금 후 재개와 10~20분 청취는 설치 앱과 일반 브라우저에서 확인해 주세요.</p><p>검색·필터·정렬·페이지 이동은 재생을 중단하지 않습니다. 다른 방송을 선택하면 앞 방송이 멈추고 새 방송이 준비됩니다. 연속재생을 켜면 현재 검색·멤버·정렬·저장 목록 순서대로 영상과 팟캐스트를 처음부터 이어 재생합니다. 자동 시작이 제한되면 공통 재생 버튼을 눌러주세요. ‘이전 목록 듣기’와 ‘다음 목록 듣기’는 현재 필터·정렬 순서의 앞뒤 방송을 처음부터 재생합니다. 목록 처음과 끝에서는 해당 방향 버튼이 비활성화됩니다. 페이지 마지막에서도 이어지며 목록 끝에서 멈춥니다. 랜덤 재생은 현재 필터의 전체 목록을 한 번씩 섞어 재생하고 한 바퀴가 끝나면 멈춥니다. 이전·다음 버튼도 그 순서를 따릅니다. 검색·필터로 목록이 바뀌면 새 순서를 만듭니다. 한 편 반복은 현재 방송을 처음부터 다시 재생하며 랜덤보다 우선합니다. 반복 중 이전·다음으로 이동하면 새 방송을 반복합니다. 재생 방식 버튼을 켜면 연속재생도 켜지며, 연속재생을 끄면 한 편 반복도 꺼집니다. 필터에서 현재 방송이 빠지면 자동으로 다른 방송을 시작하지 않습니다. 사이트의 다른 페이지로 이동하면 재생이 끝납니다. 화면 잠금 상태에서 다음 방송의 자동 시작은 기기·브라우저에 따라 제한될 수 있습니다.</p><p>최근 재생 위치와 저장한 방송은 이 브라우저에만 남습니다. 영상 파일은 저장하지 않습니다. 재생이 안 되거나 삽입이 제한되면 위의 원본 열기를 이용해 주세요.</p><p>방송사·제작 채널과 팬 보관 영상을 구분합니다. 전체본 표기가 없는 영상은 일부 방송일 수 있습니다. 같은 기록에 여러 출처가 있으면 확인된 대표 유튜브 영상 하나를 우선 표시하며, 나머지 출처는 아카이브에서 볼 수 있습니다. 채널 확인은 재생 가능 여부나 이용 권한을 보증하지 않습니다.</p><a href="/">메인 뮤비와 비교하기 →</a></details>
 <script type="application/json" id="radioData">${JSON.stringify(rows).replace(/</g,'\\u003c')}</script></section>`;
};
