const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,new URL(req.url,'http://local').pathname);try{if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(8093,'127.0.0.1',r));let browser;const passes=[],errors=[];try{
browser=await chromium.launch({channel:'msedge',headless:true});const c=await browser.newContext({viewport:{width:390,height:900}});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));const go=async r=>{await p.goto('http://127.0.0.1:8093'+r);await p.waitForLoadState('networkidle');};
await go('/archive/');assert.equal(await p.locator('.archive-card').count(),9);const first=await p.locator('.archive-card h3').first().innerText();await p.getByRole('button',{name:'다음 페이지',exact:true}).click();assert.notEqual(await p.locator('.archive-card h3').first().innerText(),first);await p.locator('#archiveSearch').fill('사랑의 인사');assert((await p.locator('#archiveCount').innerText()).includes('기록'));await p.locator('#archiveTypes [data-value="album"]').click();assert(await p.locator('.archive-card').count()>0);await p.locator('#archiveSort').selectOption('oldest');await p.locator('.archive-reset').click();assert.equal(await p.locator('.archive-card h3').first().innerText(),first);await p.locator('#archiveSearch').fill('<img src=x onerror=alert(1)>');assert.equal(await p.locator('#archiveActive img').count(),0);passes.push('Archive: search, category, pagination, sorting, reset, escaped search text');
await go('/news/');for(const name of ['씨야','남규리','김연지','이보람']){await p.locator('#newsFilter').getByRole('button',{name,exact:true}).click();await p.waitForLoadState('networkidle');assert(await p.locator('.news-card').count()>0);}passes.push('News: all four category filters');
const bank=JSON.parse(fs.readFileSync(path.join(root,'data/lyric-quiz.json')));assert.equal(bank.length,135);
await go('/game/lyrics/');
for(const level of [1,2,3]){
 await p.locator('.lyric-level-card').nth(level-1).click();
 for(let i=0;i<10;i++){
  const lyric=await p.locator('#lyricLine').innerText();const q=bank.find(x=>x.level===level&&x.lyric===lyric);assert(q);
  if(level===1)await p.locator('.lyric-choice').filter({hasText:q.song}).filter({has:p.locator(':scope')}).count();
  if(level===1){const choices=p.locator('.lyric-choice');for(let j=0;j<await choices.count();j++)if(await choices.nth(j).getAttribute('data-choice')===q.song){await choices.nth(j).click();break;}}
  else{if(i===0){await p.locator('#lyricInput').fill('오답');await p.locator('#lyricSubmit').click();assert((await p.locator('#lyricAttempt').innerText()).includes(q.album));}await p.locator('#lyricInput').fill(' '+q.song+' ');await p.locator('#lyricSubmit').click();}
  await p.locator('.lyric-next').click();
 }
 assert.equal(await p.locator('#lyricFinalScore').innerText(),level===1?'10 / 10':'9 / 10');assert.equal(await p.locator('#lyricFinishText span').count(),3);assert(!(await p.locator('#lyricFinish').innerText()).includes('ARCHIVIST'));
 await p.getByRole('button',{name:'같은 난이도로 다시 하기'}).click();assert(await p.locator('#lyricQuizStage').evaluate(e=>e.classList.contains('active')));await p.evaluate(()=>resetLyricGame());
}
passes.push('Quiz: all three levels, 135 questions, 30 answers, album hint, score excludes second try, three result lines, restart/reset');
await go('/music/fanchant/');assert.equal(await p.locator('.fanchant-image-card').count(),12);await p.locator('.fanchant-image-card').first().click();assert(await p.locator('#fanChantLightbox').evaluate(e=>e.classList.contains('open')));await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#fanChantLightboxCount').innerText(),'2 / 12');await p.keyboard.press('Escape');assert(!await p.locator('#fanChantLightbox').evaluate(e=>e.classList.contains('open')));passes.push('Fanchant: 12 cards, open, arrow navigation, Escape');
await c.route('**/data/photos.json*',r=>r.fulfill({json:[{title:'검증 사진 A',image:'/images/game/lyric-quiz-hero.png',date:'2026-09-09',member:'씨야'},{title:'검증 사진 B',image:'/images/common/seeya-pixel-characters.png',date:'2026-09-08',member:'씨야'}]}));await go('/gallery/');assert.equal(await p.locator('.gallery-card').count(),2);await p.locator('.gallery-card button').first().click();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#galleryLightboxCount').innerText(),'2 / 2');await p.keyboard.press('Escape');passes.push('Gallery: injected test data, two photos, lightbox and arrow/Escape');
await go('/');await p.locator('aside nav a[href="/music/"]').evaluate(e=>e.click());await p.waitForURL('**/music/');await p.reload();assert.equal(await p.locator('.album').count(),8);await go('/#/guide/');await p.waitForURL('**/guide/');passes.push('Normal link navigation, reload, old hash bookmark');
await go('/');await p.keyboard.type('seeyatarot');assert.equal(await p.locator('.tcard').count(),22);await p.locator('.tcard').first().click();assert(await p.locator('#modal').evaluate(e=>e.classList.contains('on')));await p.evaluate(()=>closeCard());passes.push('Hidden tarot shortcut and modal retained');
const no=await browser.newContext({javaScriptEnabled:false});await no.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const n=await no.newPage();for(const route of JSON.parse(fs.readFileSync(path.join(root,'src/data/routes.json')))){await n.goto('http://127.0.0.1:8093'+route.path);assert((await n.locator('#app').innerText()).length>100);if(route.key==='news')assert(await n.locator('.news-card').count()>0);if(route.key==='archive')assert.equal(await n.locator('.archive-card').count(),9);if(route.key==='fanchant')assert.equal(await n.locator('.fanchant-image-card').count(),12);}passes.push('JavaScript disabled: 11 routes have readable content, news/archive/fanchant populated');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'validation/functional-results.json'),JSON.stringify({passes,errors},null,2));console.log(passes.join('\n'));
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
