'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('manage/index.html'),js=read('src/admin/admin.js');
assert(html.includes('noindex,nofollow,noarchive'));
assert(html.includes("connect-src 'self' https://api.github.com"));
for(const x of ['googletagmanager','visitor-count','manifest.webmanifest','<style','<script>'])assert(!html.includes(x),x);
assert(!read('sitemap.xml').includes('/manage/'));
assert(!read('sw.js').includes('/manage/'));
assert(!js.includes('innerHTML=result.message'));
assert(!/localStorage\.setItem\([^)]*token/i.test(js));
assert(js.includes("token=''"));
for(const match of html.matchAll(/(?:href|src)="(\/assets\/[^"\s]+)"/g))assert(fs.existsSync(path.join(root,match[1])));
console.log('PASS admin: isolated login shell, no analytics/sitemap/cache entry, local assets and memory-only credential path.');
const vm=require('node:vm'),draftSource=js.slice(js.indexOf('function draft('),js.indexOf('function options('));
const context={drafts:new Map(),TYPES:{concert:'공연'},MEMBERS:['남규리','김연지','이보람']};vm.createContext(context);vm.runInContext(draftSource,context);
const item={id:'fixture',title:'이보람 직캠',sourceKind:'youtube',members:['이보람'],suggestedType:'concert',relatedRecords:[{id:'parent',strong:true}]};
assert.equal(context.draft(item).targetId,'parent');assert.equal(context.draft(item).mode,'link');
assert.equal(context.draft({...item,id:'ambiguous',relatedRecords:[{id:'a',strong:true},{id:'b',strong:true}]}).targetId,'');
assert.equal(context.draft({...item,id:'weak',relatedRecords:[{id:'a'}]}).mode,'new');
