'use strict';
const {data,esc,answered,grade,shuffledChoices,printQuestions}=require('../shared/exam');
const {papers,report}=require('../shared/exam-layout');
const root=document.getElementById('examScreen');
if(root){
 let phase='welcome',mode='paper',index=0,answers={},order=shuffledChoices(),confirming=false,candidateName='';
 const count=()=>data.questions.filter(q=>answered(q,answers[q.id])).length;
 const answerLabel=q=>q.type==='choice'?q.choices[q.answer]:q.answer;
 const jumpFocus=()=>{const h=root.querySelector('[data-focus]');if(h){h.focus({preventScroll:true});h.scrollIntoView({block:'start',behavior:'auto'});}};
 const status=()=>{const el=root.querySelector('#examProgress');if(el)el.textContent=`${count()} / 25문제 답변`;root.querySelectorAll('[data-jump]').forEach(b=>{const n=Number(b.dataset.jump),q=data.questions[n],done=answered(q,answers[q.id]);b.classList.toggle('is-answered',done);b.setAttribute('aria-label',`${n+1}번 문제${done?' · 답변 완료':' · 미응답'}`);});};
 function question(q,i){return `<fieldset class="exam-question" id="exam-q-${i}" ${mode==='card'?'':'tabindex="-1"'}><legend><span class="exam-q-meta">${q.type==='choice'?'객관식':'주관식'} · 4점</span><span class="exam-q-title">${i+1}. ${esc(q.prompt)}</span></legend>${q.type==='choice'?`<div class="exam-options">${order[i].map((v,n)=>`<label class="exam-option"><input type="radio" name="${q.id}" value="${v}" ${answers[q.id]===v?'checked':''}><span class="exam-option-number">${n+1}</span><span>${esc(q.choices[v])}</span></label>`).join('')}</div>`:`<label class="exam-input-label" for="answer-${q.id}">정답 입력</label><input class="exam-input" id="answer-${q.id}" name="${q.id}" type="text" maxlength="150" autocomplete="off" value="${esc(answers[q.id]||'')}" placeholder="답을 적어주세요"><p class="exam-help">띄어쓰기·영어 대소문자는 구분하지 않아요.</p>`}</fieldset>`;}
 function render(){
  if(phase==='result'){const result=grade(answers);root.innerHTML=report(answers,candidateName)+`<section class="exam-review"><h2>정답과 해설</h2><p>문항을 펼쳐 내 답과 해설을 확인하세요.</p>${data.questions.map((q,i)=>{const row=result.rows[i],mine=row.answered?(q.type==='choice'?q.choices[answers[q.id]]:answers[q.id]):'미응답';return `<details id="review-${q.id}" class="exam-review-item ${row.correct?'is-correct':'is-wrong'}"><summary><span class="exam-mark">${row.correct?'정답':row.answered?'오답':'미응답'}</span><span>${i+1}. ${esc(q.prompt)}</span></summary><div><p>내 답: ${esc(mine)}</p><p><b>정답: ${esc(answerLabel(q))}</b></p><p>${esc(q.explanation)}</p><a href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">근거 자료 보기 ↗</a></div></details>`;}).join('')}</section>`;jumpFocus();return;}
  root.innerHTML=`<header class="exam-heading"><div class="exam-kicker">SEEYA EXAM · 난이도 상</div><h1 tabindex="-1" data-focus>씨야 모의고사</h1><p>객관식 20문제 · 주관식 5문제 / 각 4점</p></header><div class="exam-toolbar"><div class="exam-mode" aria-label="풀이 방식"><button type="button" data-mode="paper" aria-pressed="${mode==='paper'}">시험지형</button><button type="button" data-mode="card" aria-pressed="${mode==='card'}">카드형</button></div><span id="examProgress" role="status">${count()} / 25문제 답변</span><button type="button" class="exam-text-button" data-print>시험지 인쇄</button></div><details class="exam-map"><summary>문제 바로가기 · 답변 현황</summary><div>${data.questions.map((q,i)=>`<button type="button" data-jump="${i}">${i+1}</button>`).join('')}</div><p class="exam-help">분홍색으로 채워진 번호는 답변한 문제예요.</p></details><form id="examForm" class="exam-sheet ${mode==='card'?'exam-card-mode':'exam-paper-mode'}">${mode==='card'?`<p class="exam-sheet-label">${index+1} / 25</p>${question(data.questions[index],index)}`:papers(question,candidateName)}${mode==='card'?`<div class="exam-card-nav"><button type="button" class="exam-secondary" data-step="-1" ${index===0?'disabled':''}>이전 문제</button><span>${index+1} / 25</span><button type="button" data-step="1" ${index===24?'disabled':''}>다음 문제</button></div>`:''}<div class="exam-submit"><button type="button" data-submit>답안 제출하기</button><p class="exam-help">제출 전까지 답을 수정할 수 있어요.</p></div></form><div id="examConfirm" class="exam-confirm" ${confirming?'':'hidden'} aria-label="답안 제출 확인"><h2 tabindex="-1">답안을 제출할까요?</h2><p>${25-count()?`아직 ${25-count()}문제가 비어 있어요. 미응답은 0점으로 처리됩니다.`:'25문제에 모두 답했어요. 제출하면 정답과 해설이 공개됩니다.'}</p><div class="exam-actions"><button type="button" data-finish>제출하고 결과 보기</button><button type="button" class="exam-secondary" data-cancel>계속 풀기</button></div></div>`;status();
 }
 root.addEventListener('input',e=>{const q=data.questions.find(q=>q.id===e.target.name);if(!q||phase!=='exam')return;answers[q.id]=q.type==='choice'?Number(e.target.value):e.target.value;confirming=false;const box=root.querySelector('#examConfirm');if(box)box.hidden=true;status();});
 root.addEventListener('submit',e=>e.preventDefault());
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-print')){if(phase==='welcome')candidateName=(root.querySelector('#candidateName')?.value||'').trim();document.querySelector('.exam-print').innerHTML=printQuestions(phase==='welcome'?undefined:order,candidateName);window.print();return;}
  if(b.dataset.review){const d=root.querySelector('#review-'+b.dataset.review);if(d){d.open=true;d.querySelector('summary').focus();d.scrollIntoView({block:'start'});}return;}
  if(b.dataset.start){candidateName=(root.querySelector('#candidateName')?.value||'').trim();phase='exam';mode=b.dataset.start;render();jumpFocus();return;}
  if(b.dataset.mode){mode=b.dataset.mode;confirming=false;render();jumpFocus();return;}
  if(b.dataset.step){index+=Number(b.dataset.step);index=Math.max(0,Math.min(24,index));confirming=false;render();jumpFocus();return;}
  if(b.dataset.jump!==undefined){index=Number(b.dataset.jump);if(mode==='card'){confirming=false;render();jumpFocus();}else{const q=root.querySelector('#exam-q-'+index);q.focus();q.scrollIntoView({block:'start'});}return;}
  if(b.hasAttribute('data-submit')){confirming=true;render();const box=root.querySelector('#examConfirm');box.querySelector('h2').focus();box.scrollIntoView({block:'center'});return;}
  if(b.hasAttribute('data-cancel')){confirming=false;root.querySelector('#examConfirm').hidden=true;root.querySelector('[data-submit]').focus();return;}
  if(b.hasAttribute('data-finish')&&phase==='exam'){phase='result';confirming=false;render();return;}
  if(b.hasAttribute('data-retry')){phase='exam';answers={};index=0;confirming=false;order=shuffledChoices();render();jumpFocus();}
 });
 window.addEventListener('beforeunload',e=>{if(phase==='exam'&&count()>0){e.preventDefault();e.returnValue='';}});
}
