'use strict';
const P=require('../shared/passport'),X=require('../shared/passport-extra'),E=P.esc;
module.exports=function maker(app,state,catalog,say,download,entryId=''){
 const templates={profile:'프로필',lock:'잠금화면',home:'홈화면',ticket:'티켓',review:'결산',stats:'집계'};
 const colors={ink:'#1f1b24',rose:'#d6487f',violet:'#6b5bd1',teal:'#2f8f7a',pink:'#f7dce7',cream:'#fcf8f5'};
 let type=entryId?'ticket':'lock',blob=null,serial=0;
 const opts=(items,selected)=>items.map(([v,n])=>`<option value="${E(v)}" ${v===selected?'selected':''}>${E(n)}</option>`).join('');
 app.innerHTML=`<a class="pp-back" href="/passport/test/">← 내 패스포트</a><section class="pp-panel pp-maker"><h2>이미지 만들기</h2><div class="pp-template-tabs" role="group" aria-label="이미지 템플릿">${Object.entries(templates).map(([v,n])=>`<button data-template="${v}" aria-pressed="${v===type}">${n}</button>`).join('')}</div><div class="pp-maker-layout"><div class="pp-canvas-wrap"><canvas id="ppCanvas" aria-label="내 패스포트 이미지 미리보기"></canvas><p id="ppImageSize" class="pp-help"></p></div><form id="ppMakerControls" class="pp-form-grid"><label class="pp-field"><span>색</span><select name="color">${opts(Object.keys(colors).map(k=>[k,{ink:'검정',rose:'로즈',violet:'바이올렛',teal:'틸',pink:'핑크',cream:'크림'}[k]]),'ink')}</select></label><label class="pp-field" id="ppDevice"><span>화면 크기</span><select name="device">${opts([['iphone','iPhone 일반 · 1170×2532'],['max','Pro Max · 1290×2796'],['android','Android · 1440×3120']],'iphone')}</select></label><label class="pp-field pp-wide"><span>캐릭터 그림</span><select name="character">${opts([['','없음'],...catalog.characters.map((c,i)=>[c.id,'캐릭터 일러스트 '+(i+1)])],'')}</select></label><label class="pp-field pp-wide"><span>문구</span><input name="motto" maxlength="80" value="${E(state.profile.motto)}" placeholder="함께한 기억, 앞으로의 우리"></label><label class="pp-field pp-wide" id="ppImageEntry"><span>기록 선택</span><select name="entry">${opts(state.entries.map(e=>[e.entryId,P.dateLabel(e.date)+' · '+e.title]),entryId||state.entries[0]?.entryId)}</select></label><label class="pp-field pp-wide" id="ppReviewMonth"><span>결산 기간</span><select name="period"><option value="month">월간</option><option value="year">연간</option></select><input type="month" name="month" value="${P.today().slice(0,7)}"></label><label class="pp-checks pp-wide"><input name="nickname" type="checkbox"> 닉네임 포함</label><label class="pp-checks pp-wide" id="ppSeatOpt"><input name="seat" type="checkbox"> 좌석 정보 포함</label><p class="pp-help pp-wide">메모·동행인·첨부 링크는 이미지에 포함하지 않습니다. 저장 전에 미리보기를 확인해 주세요.</p><div class="pp-actions pp-wide"><button type="button" id="ppSaveImage" class="pp-primary">이미지 저장</button><button type="button" id="ppShareMade">이미지 공유</button></div></form></div></section>`;
 const f=document.getElementById('ppMakerControls'),canvas=document.getElementById('ppCanvas');
 const text=(g,s,x,y,size,maxWidth,lineHeight,maxLines=4)=>{g.font=`${size>=44?'600 ':''}${size}px Arial, sans-serif`;let line='',row=0;for(const ch of String(s)){if(g.measureText(line+ch).width>maxWidth&&line){g.fillText(line,x,y+row*lineHeight);row++;if(row>=maxLines)return;line='';}line+=ch;}if(line)g.fillText(line,x,y+row*lineHeight);};
 async function draw(){const run=++serial;blob=null;const wallpaper=['lock','home'].includes(type),size=wallpaper?{iphone:[1170,2532],max:[1290,2796],android:[1440,3120]}[f.elements.device.value]:type==='ticket'?[1080,1350]:type==='review'?[1080,1920]:[1080,1080];canvas.width=size[0];canvas.height=size[1];const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=w/1080;g.scale(scale,scale);const H=h/scale,bg=colors[f.elements.color.value],light=['pink','cream'].includes(f.elements.color.value),fg=light?'#29232a':'#fff7fb',accent=light?'#b43764':'#f0aeca';g.fillStyle=bg;g.fillRect(0,0,1080,H);g.fillStyle=fg;
 document.getElementById('ppDevice').hidden=!wallpaper;document.getElementById('ppImageEntry').hidden=type!=='ticket';document.getElementById('ppSeatOpt').hidden=type!=='ticket';document.getElementById('ppReviewMonth').hidden=type!=='review';
 const n=P.summary(state.entries),years=state.profile.since?Number(P.today().slice(0,4))-Number(state.profile.since.slice(0,4))+1:0;
 let y=wallpaper?(type==='lock'?H*.44:H*.64):100;
 text(g,'WITH YOU PASSPORT'+(f.elements.nickname.checked&&state.profile.nickname?' · '+state.profile.nickname:''),76,y,24,920,32,1);y+=90;
 if(type==='ticket'){const e=state.entries.find(e=>e.entryId===f.elements.entry.value);if(e){text(g,e.title,76,y,54,920,76);y+=320;text(g,e.snapshot.place,76,y,30,920,45);y+=120;text(g,P.dateLabel(e.date)+(e.time?' · '+e.time:''),76,y,34,920,50);y+=100;if(f.elements.seat.checked)text(g,'좌석 · '+(e.seat||'미입력'),76,y,28,920,42);y+=75;text(g,'들은 곡 '+(e.songs||[]).length+'곡 · '+(e.status==='planned'?'갈 예정':'다녀왔어요'),76,y,30,920,44);g.strokeStyle=accent;g.setLineDash([10,10]);g.beginPath();g.moveTo(76,660);g.lineTo(1000,660);g.stroke();g.setLineDash([]);}else text(g,'먼저 기록을 남겨 주세요.',76,y,40,920,60);}
 else if(type==='lock'||type==='home'){text(g,'THE FAN · TOUR STAMPS',76,y,28,920,40);y+=85;catalog.tour.forEach((t,i)=>{const x=160+(i%4)*250,cy=y+Math.floor(i/4)*175,done=X.tourEntries(t,state.entries).length>0;g.beginPath();g.arc(x,cy,64,0,Math.PI*2);g.strokeStyle=accent;g.fillStyle=done?'#c84a74':bg;g.setLineDash(done?[]:[6,7]);g.fill();g.stroke();g.setLineDash([]);g.fillStyle=done?'#fff':fg;g.textAlign='center';text(g,t.label,x,cy+5,28,150,35,1);text(g,t.date.slice(5).replace('-','.'),x,cy-28,18,150,25,1);g.textAlign='left';});g.fillStyle=fg;y+=310;const next=catalog.tour.filter(t=>t.date>=P.today()).sort((a,b)=>a.date.localeCompare(b.date))[0];if(next)text(g,`NEXT · ${next.label} ${next.date} · D-${Math.round((Date.parse(next.date)-Date.parse(P.today()))/86400000)}`,76,y,26,920,40);}
 else if(type==='profile'){text(g,f.elements.nickname.checked?state.profile.nickname||'WITH YOU':'WITH YOU',76,y,64,920,82);y+=140;g.fillStyle=accent;text(g,years?'위듀 '+years+'년차':'우리의 첫 페이지',76,y,62,920,80);y+=110;g.fillStyle=fg;text(g,P.MEMBERS[state.profile.favMember]||'씨야 완전체',76,y,32,920,46);y+=60;text(g,state.profile.favSong||'',76,y,30,920,45);}
 else {let rows=state.entries;if(type==='review'){const period=f.elements.period.value==='year'?f.elements.month.value.slice(0,4):f.elements.month.value;rows=rows.filter(e=>e.date.startsWith(period));text(g,period+' · '+(f.elements.period.value==='year'?'올해의 나':'이달의 나'),76,y,52,920,80);}else text(g,'함께 쌓은 순간들',76,y,54,920,80);const counts=P.summary(rows);y+=145;for(const [v,label] of [[counts.concert,'공연 관람'],[counts.visit,'장소 방문'],[X.songs(rows).length,'라이브로 들은 곡']]){g.fillStyle=accent;text(g,String(v),76,y,76,920,90);g.fillStyle=fg;text(g,label,250,y,32,710,48);y+=140;}if(type==='review'){rows.filter(e=>P.completed(e)).slice(0,4).forEach(e=>{text(g,P.dateLabel(e.date)+' · '+e.title,76,y,26,920,40,2);y+=100;});}}
 const char=catalog.characters.find(c=>c.id===f.elements.character.value);if(char){try{const img=new Image();img.src=char.image;await img.decode();if(run!==serial)return;const maxH=wallpaper?190:180,ratio=Math.min(380/img.width,maxH/img.height);g.drawImage(img,680, H-110-img.height*ratio,img.width*ratio,img.height*ratio);}catch{say('캐릭터 그림을 불러오지 못했어요. 연결된 상태에서 다시 선택해 주세요.');}}
 g.fillStyle=fg;text(g,f.elements.motto.value,76,H-140,28,char?550:920,42,2);g.fillStyle=accent;text(g,'SEEYA ARCHIVE · 나의 기억으로 남긴 기록',76,H-50,18,920,28,1);document.getElementById('ppImageSize').textContent=`${w} × ${h} PNG · ${templates[type]}`;await new Promise(resolve=>canvas.toBlob(b=>{if(run===serial)blob=b;resolve();},'image/png'));
 }
 app.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{type=b.dataset.template;app.querySelectorAll('[data-template]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();});f.addEventListener('input',()=>draw());f.onsubmit=e=>e.preventDefault();document.getElementById('ppSaveImage').onclick=()=>{if(blob)download(blob,`with-you-${type}.png`);else say('이미지를 준비 중이에요. 잠시 후 다시 눌러 주세요.');};document.getElementById('ppShareMade').onclick=async()=>{if(!blob)return;const file=new File([blob],`with-you-${type}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});}catch(e){if(e.name!=='AbortError')say('공유 대신 이미지 저장을 이용해 주세요.');}}else download(blob,file.name);};draw();
};
