'use strict';
const P=require('../shared/passport');
const attachPicker=require('./passport-picker');
const X=require('../shared/passport-extra'),Share=require('./passport-share'),Maker=require('./passport-maker');
const app=document.getElementById('passportApp'),status=document.getElementById('ppStatus');
const catalog=JSON.parse(document.getElementById('passportCatalog').textContent),E=P.esc;
let store,state,dirty=false,pendingImport=null,filterKind='',filterYear='',filterMember='',listMode=false,page=1,exportURL='',renderedHash=location.hash;
const say=s=>{status.textContent=s;};
const options=(items,selected)=>items.map(([v,t])=>`<option value="${E(v)}"${v===selected?' selected':''}>${E(t)}</option>`).join('');
const field=(label,name,value='',extra='')=>`<label class="pp-field"><span>${label}</span><input name="${name}" value="${E(value)}" ${extra}></label>`;
const memberNames=e=>e.members.map(m=>P.MEMBERS[m]).join(' · ')||'멤버 미지정';
const eventKind=e=>e?.type==='performance'?'concert':'story';
const kindState=e=>e.status==='planned'?'갈 예정':e.kind==='story'?'남긴 이야기':'다녀왔어요';
function save(next){try{state=store.save(next);dirty=false;return true;}catch(error){say(error.name==='QuotaExceededError'?'저장 공간이 부족합니다. 입력 내용을 복사해 두고 수첩을 백업해 주세요.':error.message||'저장하지 못했습니다. 입력 내용을 복사해 주세요.');return false;}}
function go(hash=''){dirty=false;if(location.hash===hash)render();else location.hash=hash;}
function linkBack(){return '<a class="pp-back" href="/passport/test/">← 내 패스포트</a>';}
function profileCard(){const p=state.profile,n=P.summary(state.entries),years=p.since?Math.max(1,Number(P.today().slice(0,4))-Number(p.since.slice(0,4))+1):0;return `<div class="pp-sidebar"><section class="pp-panel pp-profile" style="--pp-color:${P.COLORS[p.color]}"><div class="pp-card-top"><span>SINCE ${E(p.since||'YOUR FIRST DAY')}</span><span>WITH YOU</span></div><div class="pp-identity"><div><p>처음 씨야를 좋아한 날</p><strong>${years?'위듀 '+years+'년차':'우리의 첫 페이지'}</strong></div><span class="pp-round-seal">SEE<br>YA</span></div><p class="pp-nickname">${E(p.nickname||'나의 패스포트')}</p><div class="pp-stats"><div><b>${n.concert}</b><span>공연 관람</span></div><div><b>${n.visit}</b><span>장소 방문</span></div><div><b>${X.songs(state.entries).length}</b><span>들은 곡 / ${catalog.songs.length}</span></div></div>${p.favSong?`<p class="pp-help">MY SONG · ${E(p.favSong)}</p>`:''}${p.motto?`<p class="pp-motto">${E(p.motto)}</p>`:''}<div class="pp-actions"><button data-action="copy-summary">집계 복사</button><a href="/passport/test/#share">QR로 공유</a></div><a class="pp-profile-edit" href="/passport/test/#profile">신분 카드 편집 →</a></section><section class="pp-panel pp-member-counts"><p class="pp-label">MEMBERS</p>${Object.entries(P.MEMBERS).map(([id,name])=>`<div><span class="pp-member-dot" data-member="${id}"></span><span>${name}</span><b>${state.entries.filter(e=>P.completed(e)&&e.members.includes(id)).length}</b></div>`).join('')}</section><div class="pp-storage-note"><b>이 브라우저에 저장돼요</b><p>기기를 바꾸기 전에 백업해 주세요.<br>기록은 다른 사람과 비교하지 않아요.</p><a href="/passport/test/#settings">백업·복원</a> · <a href="/about/install/">홈 화면에 추가</a></div></div>`;}
function tour(){const total=catalog.tour.filter(t=>X.tourEntries(t,state.entries).length).length;return `<section class="pp-tour-section"><div class="pp-section-head"><div><p class="pp-label">THE FAN · 20TH ANNIVERSARY TOUR</p><h2>투어 도장판 <small>${total} / ${catalog.tour.length}</small></h2></div><a href="/calendar/">일정 보기</a></div><div class="pp-panel pp-tour">${catalog.tour.map(t=>{const records=X.tourEntries(t,state.entries),planned=state.entries.some(x=>x.eventId===t.eventId&&x.date===t.date&&x.status==='planned'),diff=Math.round((Date.parse(t.date)-Date.parse(P.today()))/86400000);return `<button class="pp-stamp${records.length?' is-done':''}" data-event="${E(t.eventId)}" aria-label="${E(t.label+' '+P.dateLabel(t.date))} 공연 기록하기"><strong><small>${t.date.slice(5).replace('-','.')}</small>${E(t.label)}</strong><span>${records.length?'관람 '+records.length+'회':planned?'갈 예정':diff>0?'D-'+diff:diff===0?'오늘':'추억 남기기'}</span></button>`;}).join('')}</div></section>`;}
function home(){let rows=state.entries.filter(e=>(!filterKind||e.kind===filterKind)&&(!filterYear||e.date.slice(0,4)===filterYear)&&(!filterMember||e.members.includes(filterMember))).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||b.createdAt.localeCompare(a.createdAt));const pages=Math.max(1,Math.ceil(rows.length/9));page=Math.min(page,pages);const years=[...new Set(state.entries.map(e=>e.date.slice(0,4)).filter(Boolean))].sort().reverse();app.innerHTML=`<div class="pp-layout">${profileCard()}<div>${tour()}<div class="pp-toolbar"><h2>내 기록 <small>${rows.length}</small></h2><button data-action="view" aria-pressed="${listMode}">${listMode?'스탬프 보기':'시간순 보기'}</button><div class="pp-filters"><select id="ppYearFilter" aria-label="기록 연도 필터">${options([['','모든 연도'],...years.map(y=>[y,y+'년'])],filterYear)}</select><select id="ppKindFilter" aria-label="기록 종류 필터">${options([['','모든 종류'],...Object.entries(P.KINDS)],filterKind)}</select><select id="ppMemberFilter" aria-label="기록 멤버 필터">${options([['','모든 멤버'],...Object.entries(P.MEMBERS)],filterMember)}</select></div></div>${rows.length?`<div class="pp-records${listMode?' is-list':''}">${rows.slice((page-1)*9,page*9).map(e=>`<a href="/passport/test/#entry=${encodeURIComponent(e.entryId)}" class="pp-record" data-kind="${e.kind}"><span class="pp-label">${{concert:'CONCERT · TICKET',visit:'VISIT',event:'FAN EVENT',story:'MY STORY'}[e.kind]}</span><h3>${E(e.title)}</h3><p>${P.dateLabel(e.date)}${e.time?' · '+e.time:''}</p><p>${E(e.snapshot.place||memberNames(e))}</p><div class="pp-record-foot"><span>${e.kind==='concert'?(e.songs||[]).length+'곡 · ':''}${kindState(e)}</span><span class="pp-member-dot" data-member="${e.members[0]||'seeya'}"></span></div></a>`).join('')}</div><div class="pp-pagination"><button data-page="${page-1}" ${page===1?'disabled':''}>이전</button><span>${page} / ${pages}</span><button data-page="${page+1}" ${page===pages?'disabled':''}>다음</button></div>`:`<div class="pp-empty"><div class="pp-empty-stamps" aria-hidden="true">TICKET　 VISIT　 MY STORY</div><strong>처음 씨야를 좋아한 날부터.</strong><p>날짜가 정확하지 않아도 괜찮아요.<br>한 장의 기억으로 수첩을 시작해 보세요.</p><a href="/passport/test/#profile">처음 좋아한 날 남기기 →</a></div>`}<a class="pp-new-bottom" href="/passport/test/#new">＋ 기록 남기기</a></div></div>`;}

function ticket(e){return `<div class="pp-ticket"><p class="pp-label">WITH YOU PASSPORT · ${P.KINDS[e.kind]}</p><h2>${E(e.title)}</h2><p>${E(e.snapshot.place||'나의 기억 속 한 장면')}</p><div class="pp-ticket-cut"><p>${P.dateLabel(e.date)}${e.time?' · '+e.time:''}</p>${e.seat?`<p>좌석 · ${E(e.seat)}</p>`:''}<p>${E(memberNames(e))}</p><span class="pp-seal">${e.status==='planned'?'TO BE THERE':e.kind==='story'?'MY MEMORY':'I WAS HERE'}</span></div></div>`;}
function detail(id){const e=state.entries.find(e=>e.entryId===id);if(!e){app.innerHTML=linkBack()+'<p>기록을 찾지 못했어요. 백업 파일에서 복원할 수 있습니다.</p>';return;}const place=catalog.places.find(p=>p.id===e.placeId),event=catalog.events.find(x=>x.id===e.eventId);app.innerHTML=linkBack()+`<div class="pp-detail"><div>${ticket(e)}<div class="pp-actions" style="margin-top:18px"><a href="/passport/test/#make=${E(id)}">이미지로 만들기</a><a href="/passport/test/#share">QR로 공유</a><a href="/passport/test/#edit=${E(id)}">수정</a></div><p class="pp-help">공유 이미지에는 메모·동행인이 포함되지 않아요. 좌석은 이미지 만들기에서 직접 선택할 때만 포함합니다.</p></div><section class="pp-panel"><h2>그날의 기억</h2><dl><dt>상태</dt><dd>${kindState(e)}</dd><dt>날짜</dt><dd>${P.dateLabel(e.date)}</dd><dt>함께</dt><dd>${E(e.companions||'기록하지 않았어요')}</dd><dt>정보 기준</dt><dd>${e.eventId?'일정에서 시작한 기록':e.placeId?'지도에서 시작한 기록':'직접 입력'}</dd></dl>${detailExtras(e)}<p class="pp-note">${E(e.note||'아직 메모가 없어요.')}</p><div class="pp-actions">${place?`<a href="/map/?place=${encodeURIComponent(place.id)}">지도에서 보기</a>`:''}${event?.calendar?`<a href="/calendar/?month=${event.date.slice(0,7)}&event=${encodeURIComponent(event.id)}">연결된 일정</a>`:''}${e.archiveId&&catalog.events.some(x=>x.archiveId===e.archiveId)?`<a href="/archive/?record=${encodeURIComponent(e.archiveId)}">아카이브 기록</a>`:''}</div>${(e.eventId&&!event||e.placeId&&!place)?'<p class="pp-help">공개 정보의 연결이 사라졌지만 작성 당시 내용은 수첩에 남아 있어요.</p>':''}<div class="pp-danger"><button data-action="show-delete">이 기록 삭제</button><div id="ppDelete" class="pp-confirm" hidden><p>삭제 후에는 백업 파일이 있어야 복원할 수 있어요.</p><button data-delete="${E(id)}">이 기록을 삭제합니다</button></div></div></section></div><div id="ppExportResult"></div>`;}
function songFields(e){const known=new Set(catalog.songs.map(s=>s.id)),unknown=(e.songs||[]).filter(id=>!known.has(id));return `<fieldset class="pp-wide pp-song-box" id="ppSongBox" ${e.kind==='concert'?'':'hidden'}><legend>그날 들은 곡</legend><input id="ppSongSearch" type="search" placeholder="곡명 검색" aria-label="들은 곡 검색"><div class="pp-song-list">${[...catalog.songs,...unknown.map(id=>({id,title:id,album:'이전 백업의 곡'}))].map(s=>`<label data-song-title="${E(s.title.toLowerCase())}"><input type="checkbox" name="song" value="${E(s.id)}" ${(e.songs||[]).includes(s.id)?'checked':''}><span>${E(s.title)}<small>${E(s.album||'')}</small></span></label>`).join('')}</div><p class="pp-help">공연에서 실제 들은 곡만 체크해 주세요. 예정 기록은 들은 곡 집계에서 제외합니다.</p></fieldset>`;}
function linkFields(e){return `<section class="pp-wide pp-link-fields"><h3>관련 링크 <small>최대 8개</small></h3><p class="pp-help">인스타그램·유튜브·X 등 관련 게시물의 https:// 주소를 적어 주세요.</p><div id="ppLinkRows">${(e.links||[]).map((l,i)=>linkRow(l,i)).join('')}</div><button type="button" id="ppAddLink">＋ 링크 추가</button></section>`;}
function linkRow(l,i){return `<div class="pp-link-row"><label class="pp-field"><span>링크 주소 ${i+1}</span><input data-url type="url" maxlength="2000" value="${E(l.url)}" placeholder="https://"></label><label class="pp-field"><span>한 줄 설명 ${i+1}</span><input data-label maxlength="120" value="${E(l.label)}" placeholder="직접 찍은 공연 영상"></label><button type="button" data-remove-link aria-label="링크 ${i+1} 삭제">삭제</button></div>`;}
function readLinks(f){return [...f.querySelectorAll('.pp-link-row')].map(r=>({url:r.querySelector('[data-url]').value.trim(),label:r.querySelector('[data-label]').value.trim()})).filter(x=>x.url||x.label).map(x=>{if(!x.url)throw Error('설명이 있는 링크의 주소를 입력해 주세요.');return {...x,url:X.url(x.url)};});}
function wireExtras(f){f.elements.kind.addEventListener('change',()=>{document.getElementById('ppSongBox').hidden=f.elements.kind.value!=='concert';});document.getElementById('ppSongSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();f.querySelectorAll('[data-song-title]').forEach(r=>r.hidden=!r.dataset.songTitle.includes(q));};document.getElementById('ppAddLink').onclick=()=>{const box=document.getElementById('ppLinkRows');if(box.children.length>=8){say('링크는 최대 8개까지 넣을 수 있어요.');return;}box.insertAdjacentHTML('beforeend',linkRow({url:'',label:''},box.children.length));dirty=true;box.lastElementChild.querySelector('input').focus();};f.addEventListener('click',e=>{if(e.target.closest('[data-remove-link]')){e.target.closest('.pp-link-row').remove();dirty=true;}});}
function detailExtras(e){const first=new Set(X.firstSongs(e,state.entries));return `${e.kind==='concert'?`<section class="pp-detail-songs"><h3>그날 들은 곡 <small>${(e.songs||[]).length}</small></h3>${(e.songs||[]).length?`<ul>${e.songs.map(id=>`<li>${E(catalog.songs.find(s=>s.id===id)?.title||id)} ${first.has(id)&&e.status==='done'?'<small class="pp-first" title="내 수첩에 기록한 첫 청취">FIRST</small>':''}</li>`).join('')}</ul>`:'<p class="pp-help">기록 수정에서 들은 곡을 체크할 수 있어요.</p>'}</section>`:''}${e.links?.length?`<section class="pp-attached"><h3>함께 남긴 링크</h3>${e.links.map(l=>{const yt=X.youtube(l.url);return `<a href="${E(l.url)}" target="_blank" rel="noopener noreferrer">${yt?`<img src="https://i.ytimg.com/vi/${yt}/mqdefault.jpg" alt="유튜브 영상 썸네일" loading="lazy" referrerpolicy="no-referrer">`:''}<span>${E(l.label||new URL(l.url).hostname)} ↗</span></a>`;}).join('')}</section>`:''}`;}
async function copyText(text){try{await navigator.clipboard.writeText(text);say('복사했어요. 원하는 곳에 붙여넣어 주세요.');}catch{say('자동 복사를 사용할 수 없어요. 아래 문구를 선택해 복사해 주세요.');const t=document.createElement('textarea');t.value=text;t.readOnly=true;status.append(t);t.select();}}
function monthPage(){app.innerHTML=linkBack()+`<section class="pp-panel"><p class="pp-label">MY MONTH · WITH YOU</p><h2>이달의 나</h2><label class="pp-field"><span>기록을 돌아볼 달</span><input id="ppMonth" type="month" value="${P.today().slice(0,7)}"></label><div id="ppMonthResult"></div><a href="/passport/test/#make">결산 이미지 만들기 →</a></section>`;const draw=()=>{const m=document.getElementById('ppMonth').value,rows=state.entries.filter(e=>e.date.startsWith(m)&&P.completed(e)),n=P.summary(rows);document.getElementById('ppMonthResult').innerHTML=`<div class="pp-stats"><div><b>${n.concert}</b><span>공연</span></div><div><b>${n.visit}</b><span>장소</span></div><div><b>${X.songs(rows).length}</b><span>들은 곡</span></div></div>${rows.length?rows.map(e=>`<p><a href="/passport/test/#entry=${E(e.entryId)}">${P.dateLabel(e.date)} · ${E(e.title)}</a></p>`).join(''):'<p>이달의 기억을 기다리고 있어요.</p>'}`;};document.getElementById('ppMonth').onchange=draw;draw();}
function sharePage(){app.innerHTML=linkBack()+`<section class="pp-panel pp-settings"><p class="pp-label">WITH YOU · SHARE</p><h2>나의 패스포트 요약 QR</h2><p>처음 좋아한 날, 공연·장소·팬 행사·이야기 집계와 완료한 기록의 제목·날짜, 들은 곡 수를 공유합니다. 메모·좌석·동행인·첨부 링크는 제외합니다.</p><p class="pp-help">내용이 주소 안에 담깁니다. 링크를 받은 사람은 누구나 요약을 볼 수 있으며 나중에 회수할 수 없습니다. 공유 전에 기록 제목도 확인해 주세요.</p><label class="pp-checks"><input type="checkbox" id="ppShareName"> 닉네임도 포함</label><button id="ppBuildQR" class="pp-primary">요약 미리보기·QR 만들기</button><div id="ppQRResult"></div></section>`;document.getElementById('ppBuildQR').onclick=async()=>{const target=document.getElementById('ppQRResult');try{const result=await Share.make(state,document.getElementById('ppShareName').checked,location.origin+'/passport/test/#view=');if(!target.isConnected)return;target.innerHTML=`<p class="pp-help">최근 기록 ${result.included}개 포함 · 전체 집계는 유지합니다.${result.included<state.entries.filter(e=>P.completed(e)).length?' QR 용량에 맞춰 최근 기록부터 담았습니다.':''}</p><div id="ppQRCanvas"></div><label class="pp-field"><span>공유 주소</span><textarea readonly id="ppShareURL">${E(result.url)}</textarea></label><div class="pp-actions"><button id="ppCopyURL">주소 복사</button><button id="ppSaveQR">QR 이미지 저장</button><a href="${E(result.url)}" target="_blank" rel="noopener noreferrer">읽기 전용 미리보기</a></div><details><summary>공유되는 기록 확인</summary>${result.summary.r.map(r=>`<p>${E(r.d+' · '+r.t)}</p>`).join('')}</details>`;document.getElementById('ppQRCanvas').append(result.canvas);document.getElementById('ppCopyURL').onclick=()=>copyText(result.url);document.getElementById('ppSaveQR').onclick=()=>result.canvas.toBlob(b=>download(b,'with-you-summary-qr.png'),'image/png');}catch{say('이 브라우저에서는 QR을 만들지 못했어요. 최신 브라우저에서 다시 시도해 주세요.');}};}
async function viewShare(token){document.querySelector('.pp-tabs').hidden=true;app.innerHTML='<p>공유된 패스포트를 여는 중이에요.</p>';try{const s=await Share.decode(token);if(location.hash!=='#view='+token)return;app.innerHTML=`<section class="pp-panel pp-shared"><p class="pp-label">WITH YOU PASSPORT · READ ONLY</p><h2>${E(s.n||'위듀의 패스포트')}</h2><p>본인이 기록한 패스포트 요약입니다.</p><div class="pp-stats"><div><b>${s.c.concert}</b><span>공연 관람</span></div><div><b>${s.c.visit}</b><span>장소 방문</span></div><div><b>${s.c.event}</b><span>팬 행사</span></div></div><div class="pp-tour">${catalog.tour.map(t=>`<div class="pp-stamp ${s.r.some(r=>r.k==='concert'&&r.d===t.date&&(r.i===t.eventId||r.a===t.archiveId))?'is-done':''}"><strong><small>${t.date.slice(5)}</small>${E(t.label)}</strong></div>`).join('')}</div><p class="pp-help">도장은 공유에 포함된 최근 기록 기준입니다.</p><div class="pp-records">${s.r.map(r=>`<div class="pp-record" data-kind="${r.k}"><span class="pp-label">${P.KINDS[r.k]}</span><h3>${E(r.t)}</h3><p>${P.dateLabel(r.d)}</p><p>들은 곡 ${r.z}곡</p></div>`).join('')}</div></section><a href="/passport/test/">내 기기의 패스포트 열기 →</a>`;}catch{app.innerHTML='<section class="pp-panel"><h2>공유 주소를 확인해 주세요.</h2><p>주소가 잘렸거나 지원하지 않는 공유 내용입니다.</p></section>';}}

function editor(existing,params=new URLSearchParams()){
 const ev=catalog.events.find(x=>x.id===params.get('event')),pl=catalog.places.find(x=>x.id===(params.get('place')||ev?.placeId));
 const now=new Date().toISOString(),e=existing||{entryId:crypto.randomUUID(),kind:ev?eventKind(ev):pl?'visit':'story',status:ev?P.defaultStatus(ev.date):pl?'planned':'done',title:ev?.title||pl?.name||'',date:ev?.date||'',time:ev?.time||'',members:ev?.members||[],eventId:ev?.id||'',placeId:pl?.id||'',archiveId:ev?.archiveId||'',snapshot:{title:ev?.title||'',place:pl?.name||ev?.venue||'',address:pl?.address||''},seat:'',companions:'',note:'',createdAt:now,updatedAt:now};
 e.songs=e.songs||[];e.links=e.links||[];const parts=e.date.split('-');app.innerHTML=linkBack()+`<section class="pp-panel pp-editor"><h2>${existing?'기록 수정':'새 기록 남기기'}</h2><form id="ppEntryForm" class="pp-form-grid"><label class="pp-field"><span>기록 종류</span><select name="kind">${options(Object.entries(P.KINDS),e.kind)}</select></label><label class="pp-field"><span>기록 상태</span><select name="status">${options([['planned','갈 예정 / 계획'],['done','다녀왔어요 / 남긴 이야기']],e.status)}</select></label><div class="pp-wide pp-event-picker"><label class="pp-field" for="ppEventSearch"><span>등록된 일정 찾기 (선택)</span></label><input id="ppEventSearch" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="ppEventList" aria-describedby="ppEventHint" placeholder="공연명·장소·날짜 검색" autocomplete="off"><div id="ppEventList" class="pp-event-results" role="listbox" aria-label="검색된 일정" hidden></div><p id="ppEventHint" class="pp-help" role="status">검색 결과를 선택하면 제목·날짜·장소가 채워져요.</p><div id="ppSelectedEvent" class="pp-selected-event" hidden></div><div id="ppSessions" class="pp-sessions" role="group" aria-label="공연 날짜 선택" hidden></div></div><div class="pp-wide">${field('제목 *','title',e.title,'required maxlength="160"')}</div><div class="pp-wide"><span>날짜 (아는 만큼만)</span><div class="pp-date-fields">${field('연도','year',parts[0]||'','type="number" min="1900" max="2100" placeholder="미상"')}${field('월','month',parts[1]||'','type="number" min="1" max="12" placeholder="선택"')}${field('일','day',parts[2]||'','type="number" min="1" max="31" placeholder="선택"')}</div><p class="pp-help">날짜를 모두 비우면 ‘날짜 미상’으로 남아요.</p></div>${field('시간 (선택)','time',e.time,'type="time"')}${field('좌석 (선택)','seat',e.seat,'maxlength="100"')}${field('장소 이름 (직접 수정 가능)','place',e.snapshot.place,'maxlength="300"')}${field('함께 간 사람 (선택)','companions',e.companions,'maxlength="120"')}<fieldset class="pp-wide"><legend>함께한 멤버</legend><div class="pp-checks">${Object.entries(P.MEMBERS).map(([v,t])=>`<label><input type="checkbox" name="member" value="${v}"${e.members.includes(v)?' checked':''}>${t}</label>`).join('')}</div></fieldset>${songFields(e)}${linkFields(e)}<label class="pp-field pp-wide"><span>나만의 메모</span><textarea name="note" maxlength="4000" placeholder="그날의 마음을 적어 주세요.">${E(e.note)}</textarea></label><div class="pp-wide pp-draft-preview"><p class="pp-label">기록 미리보기</p><div id="ppDraft" class="pp-preview-summary"></div></div><div class="pp-wide pp-confirm" id="ppDuplicate" hidden><p>같은 날짜·회차의 비슷한 기록이 있어요.</p><label><input type="checkbox" name="allowDuplicate"> 별도의 경험으로 추가할게요</label></div><div class="pp-wide pp-actions"><button type="submit" class="pp-primary">${existing?'변경 내용 저장':'수첩에 기록하기'}</button><a href="/passport/test/">취소</a></div></form></section>`;
 const f=document.getElementById('ppEntryForm');wireExtras(f);let eventId=e.eventId,placeId=e.placeId,archiveId=e.archiveId,snapshot={...e.snapshot},statusManual=false;
 const preview=()=>{document.getElementById('ppDraft').innerHTML=ticket({title:f.elements.title.value||'나의 기록',kind:f.elements.kind.value,status:f.elements.status.value,date:[f.elements.year.value,f.elements.month.value,f.elements.day.value].filter(Boolean).join('-'),time:f.elements.time.value,seat:f.elements.seat.value,members:[...f.querySelectorAll('[name=member]:checked')].map(b=>b.value),snapshot:{place:f.elements.place.value}});};preview();
 f.addEventListener('input',ev=>{dirty=true;if(ev.target.name==='allowDuplicate')return;document.getElementById('ppDuplicate').hidden=true;if(f.elements.allowDuplicate)f.elements.allowDuplicate.checked=false;preview();});
 f.elements.place.addEventListener('change',()=>{if(f.elements.place.value!==snapshot.place){placeId='';snapshot.address='';}});
 function selectedEvent(x){const box=document.getElementById('ppSelectedEvent'),sessions=document.getElementById('ppSessions');box.hidden=!x;box.innerHTML=x?`<div><small>연결된 일정</small><strong>${E(x.date+' · '+x.title)}</strong></div><button type="button" id="ppUnlinkEvent">연결 해제</button>`:'';const group=catalog.tour.find(t=>(t.eventIds||[t.eventId]).includes(x?.id));const choices=group?(group.eventIds||[group.eventId]).map(id=>catalog.events.find(x=>x.id===id)).filter(Boolean):[];sessions.hidden=choices.length<2;sessions.innerHTML=choices.length>1?'<p>공연 날짜를 선택해 주세요.</p><div>'+choices.map(v=>`<button type="button" data-session="${E(v.id)}" aria-pressed="${f.elements.year.value+'-'+String(f.elements.month.value).padStart(2,'0')+'-'+String(f.elements.day.value).padStart(2,'0')===v.date}">${E(P.dateLabel(v.date))}</button>`).join('')+'</div>':'';}
 function chooseEvent(x){dirty=true;statusManual=false;const p=catalog.places.find(p=>p.id===x.placeId);eventId=x.id;placeId=p?.id||'';archiveId=x.archiveId;snapshot={title:x.title,place:p?.name||x.venue,address:p?.address||''};for(const [k,v] of Object.entries({title:x.title,year:x.date.slice(0,4),month:Number(x.date.slice(5,7)),day:Number(x.date.slice(8,10)),time:x.time,place:snapshot.place,kind:eventKind(x),status:P.defaultStatus(x.date)}))f.elements[k].value=v;f.querySelectorAll('[name=member]').forEach(b=>b.checked=x.members.includes(b.value));document.getElementById('ppSongBox').hidden=f.elements.kind.value!=='concert';document.getElementById('ppDuplicate').hidden=true;f.elements.allowDuplicate.checked=false;selectedEvent(x);preview();}
 selectedEvent(catalog.events.find(x=>x.id===eventId));
 attachPicker(document.getElementById('ppEventSearch'),document.getElementById('ppEventList'),document.getElementById('ppEventHint'),catalog.events,chooseEvent,E);
 f.addEventListener('click',ev=>{const b=ev.target.closest('button');if(b?.dataset.session){chooseEvent(catalog.events.find(x=>x.id===b.dataset.session));}else if(b?.id==='ppUnlinkEvent'){dirty=true;eventId='';archiveId='';selectedEvent(null);}});
 f.elements.status.addEventListener('change',()=>{statusManual=true;});
 for(const key of ['year','month','day'])f.elements[key].addEventListener('change',()=>{if(existing||statusManual)return;const y=f.elements.year.value,m=f.elements.month.value,d=f.elements.day.value,dt=y+(m?'-'+m.padStart(2,'0'):'')+(d?'-'+d.padStart(2,'0'):'');try{if(dt)f.elements.status.value=P.defaultStatus(P.date(dt));}catch{}preview();});
 f.addEventListener('submit',ev=>{ev.preventDefault();try{const y=f.elements.year.value,m=f.elements.month.value,d=f.elements.day.value;if((m&&!y)||(d&&(!y||!m)))throw Error('월·일을 입력하려면 앞의 연도·월도 입력해 주세요.');const dt=y+(m?'-'+m.padStart(2,'0'):'')+(d?'-'+d.padStart(2,'0'):'');const v=P.entry({...e,title:f.elements.title.value,kind:f.elements.kind.value,status:f.elements.status.value,date:dt,time:f.elements.time.value,seat:f.elements.seat.value,companions:f.elements.companions.value,note:f.elements.note.value,songs:[...f.querySelectorAll('[name=song]:checked')].map(b=>b.value),links:readLinks(f),members:[...f.querySelectorAll('[name=member]:checked')].map(b=>b.value),eventId,placeId,archiveId,snapshot:{...snapshot,place:f.elements.place.value},updatedAt:new Date().toISOString()});if(v.status==='done'&&v.date>P.today().slice(0,v.date.length))throw Error('미래 날짜는 ‘갈 예정’으로 저장해 주세요.');if(state.entries.some(x=>x.entryId!==e.entryId&&P.duplicate(x,v))&&!f.elements.allowDuplicate.checked){document.getElementById('ppDuplicate').hidden=false;document.getElementById('ppDuplicate').scrollIntoView({block:'center'});return;}const entries=state.entries.filter(x=>x.entryId!==e.entryId).concat(v);if(save({...state,entries})){say('수첩에 저장했어요.');go('#entry='+v.entryId);}}catch(err){say(err.message);status.scrollIntoView({block:'center'});}});
}
function editProfile(){const p=state.profile;app.innerHTML=linkBack()+`<section class="pp-panel pp-settings"><h2>나의 신분 카드</h2><form id="ppProfile" class="pp-form-grid">${field('닉네임','nickname',p.nickname,'maxlength="30"')}${field('처음 좋아한 날','since',p.since,'placeholder="2006 또는 2006-03-12" maxlength="10"')}<p class="pp-help pp-wide">데뷔일인 2006년 3월 12일부터 오늘까지 입력할 수 있어요.<br>2006년·2006년 3월처럼 날짜를 모르면 해당 연도나 월까지만 적어도 괜찮아요.</p><label class="pp-field"><span>카드 색</span><select name="color">${options([['rose','로즈'],['violet','바이올렛'],['teal','그린'],['ink','잉크']],p.color)}</select></label><label class="pp-field"><span>최애 멤버</span><select name="favMember">${options(Object.entries(P.MEMBERS),p.favMember)}</select></label><label class="pp-field"><span>최애 곡</span><select name="favSong">${options([['','선택 안 함'],...catalog.songs.map(s=>[s.title,s.title])],p.favSong)}</select></label>${field('응원 문구','motto',p.motto,'maxlength="120"')}<button class="pp-primary" type="submit">신분 카드 저장</button></form></section>`;const f=document.getElementById('ppProfile');f.addEventListener('input',()=>dirty=true);f.addEventListener('submit',e=>{e.preventDefault();try{const p=P.profile(Object.fromEntries(new FormData(f)));if(p.since>P.today().slice(0,p.since.length))throw Error('입덕일은 오늘 이전으로 입력해 주세요.');if(save({...state,profile:p})){say('신분 카드를 저장했어요.');go('');}}catch(e){say(e.message);}});}
function settings(){let last='';try{last=localStorage.getItem('seeya-passport-backup-date')||'';}catch{}app.innerHTML=linkBack()+`<div class="pp-settings"><section class="pp-panel"><h2>기록을 안전하게 가져가기</h2><p>현재 이 브라우저에 ${state.entries.length}개의 기록이 있어요. 다른 기기에서는 아래 백업 파일을 가져와 이어 쓸 수 있습니다.</p><button data-action="backup" class="pp-primary">백업 파일 내려받기</button><p class="pp-help">마지막 백업 요청: ${E(last||'아직 없어요')}<br>다운로드 후 파일이 실제로 저장됐는지 확인해 주세요.</p><a href="/about/install/">홈 화면에 추가하는 방법 →</a></section><section class="pp-panel"><h2>백업 가져오기</h2><p>내용을 먼저 확인한 다음 적용합니다. 잘못된 파일은 기존 기록을 바꾸지 않습니다.</p><input id="ppImport" type="file" accept="application/json,.json" aria-label="백업 JSON 파일 선택"><div id="ppImportPreview"></div></section><section class="pp-panel pp-danger"><h2>이 브라우저의 수첩 비우기</h2><p>신분 카드와 모든 개인 기록을 삭제합니다. 먼저 백업을 내려받아 주세요.</p><label class="pp-field"><span>계속하려면 ‘삭제’를 입력하세요.</span><input id="ppDeleteAllText" autocomplete="off"></label><button data-action="delete-all">전체 삭제</button></section></div>`;document.getElementById('ppImport').addEventListener('change',async ev=>{pendingImport=null;const preview=document.getElementById('ppImportPreview');preview.textContent='';const file=ev.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('8MB 이하의 백업 파일을 선택해 주세요.');const value=P.validate(JSON.parse(await file.text()));if(!preview.isConnected)return;const r=P.review(state,value);pendingImport=value;preview.innerHTML=`<div class="pp-confirm"><p>새 기록 ${r.added}건 · 같은 ID ${r.conflicts}건 · 중복 의심 ${r.suspected}건</p><p>가져올 신분 카드: ${E(value.profile.nickname||'이름 없음')}</p><label class="pp-field"><span>같은 ID 처리</span><select id="ppImportMode"><option value="keep">현재 기록 유지</option><option value="replace">가져온 기록으로 교체</option></select></label><label><input id="ppImportProfile" type="checkbox"> 신분 카드도 가져오기</label><p class="pp-help">다른 ID의 중복 의심 기록은 합치지 않습니다. 적용 전 백업을 권장합니다.</p><button data-action="apply-import" class="pp-primary">확인한 내용 가져오기</button></div>`;}catch(e){say('가져오지 않았습니다. '+(e instanceof SyntaxError?'JSON 백업 파일을 확인해 주세요.':e.message));}});}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function backup(){download(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),`seeya-passport-${P.today()}-${state.entries.length}entries.json`);try{localStorage.setItem('seeya-passport-backup-date',P.today());}catch{}say('백업 다운로드를 요청했어요. 파일 저장을 확인해 주세요.');}
function render(){if(location.hash.startsWith('#view=')){viewShare(location.hash.slice(6));return;}document.querySelector('.pp-tabs').hidden=false;document.querySelectorAll('.pp-tabs a').forEach(a=>{const active=location.hash.startsWith('#make')?'#make':location.hash.startsWith('#new')?'#new':location.hash;const selected=new URL(a.href).hash===active;if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(P.beforeDebut(state.profile.since))say('기존 입덕일이 데뷔일 이전이에요. 신분 카드에서 날짜를 수정해 주세요. 기존 기록은 그대로 보관했습니다.');renderedHash=location.hash;if(exportURL){URL.revokeObjectURL(exportURL);exportURL='';}pendingImport=null;const h=location.hash.slice(1);if(h==='make'||h.startsWith('make='))Maker(app,state,catalog,say,download,h.startsWith('make=')?h.slice(5):'');else if(h==='share')sharePage();else if(h==='month')monthPage();else if(h==='tour')app.innerHTML=linkBack()+tour();else if(h==='settings')settings();else if(h==='profile')editProfile();else if(h==='new'||h.startsWith('new?'))editor(null,new URLSearchParams(h.split('?')[1]||''));else if(h.startsWith('edit=')){const e=state.entries.find(x=>x.entryId===h.slice(5));if(e)editor(e);else detail(h.slice(5));}else if(h.startsWith('entry='))detail(h.slice(6));else home();}
app.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b||!store)return;if(b.dataset.action==='copy-summary'){copyText(X.summaryText(state));return;}if(b.dataset.event){go('#new?event='+encodeURIComponent(b.dataset.event));return;}if(b.dataset.page){page=Number(b.dataset.page);home();return;}if(b.dataset.delete){if(save({...state,entries:state.entries.filter(x=>x.entryId!==b.dataset.delete)})){say('기록을 삭제했어요.');go('');}return;}switch(b.dataset.action){case 'view':listMode=!listMode;home();break;case 'show-delete':document.getElementById('ppDelete').hidden=false;break;case 'backup':backup();break;case 'delete-all':if(document.getElementById('ppDeleteAllText').value!=='삭제'){say('확인란에 ‘삭제’를 입력해 주세요.');break;}if(save(P.empty())){say('이 브라우저의 개인 수첩을 비웠어요.');go('');}break;case 'apply-import':if(pendingImport){try{const next=P.merge(state,pendingImport,document.getElementById('ppImportMode').value==='replace',document.getElementById('ppImportProfile').checked);if(save(next)){say('백업을 가져왔어요.');go('');}}catch(e){say(e.message);}}break;}});
app.addEventListener('change',e=>{if(e.target.id==='ppMemberFilter'){filterMember=e.target.value;page=1;home();}if(e.target.id==='ppKindFilter'){filterKind=e.target.value;page=1;home();}if(e.target.id==='ppYearFilter'){filterYear=e.target.value;page=1;home();}});
function confirmDiscard(leave){
 if(document.getElementById('ppDiscard'))return;
 const panel=document.createElement('div');panel.id='ppDiscard';panel.className='pp-discard';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','ppDiscardTitle');
 panel.innerHTML='<div class="pp-panel"><h2 id="ppDiscardTitle">아직 저장하지 않은 입력이 있어요.</h2><p>이동하면 지금 작성 중인 내용은 사라집니다.</p><div class="pp-actions"><button id="ppStay">계속 작성</button><button id="ppLeave">저장하지 않고 이동</button></div></div>';
 const prior=document.activeElement;document.querySelector('.passport-page').append(panel);
 const stay=panel.querySelector('#ppStay'),exit=panel.querySelector('#ppLeave');stay.focus();
 stay.onclick=()=>{panel.remove();prior?.focus();};exit.onclick=()=>{panel.remove();dirty=false;leave();};
 panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();stay.click();}if(e.key==='Tab'){e.preventDefault();(document.activeElement===stay?exit:stay).focus();}});
}
document.addEventListener('click',e=>{if(!dirty)return;const a=e.target.closest('a');if(a){e.preventDefault();confirmDiscard(()=>location.href=a.href);}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>{if(dirty){const target=location.hash;history.replaceState(null,'',location.pathname+location.search+renderedHash);confirmDiscard(()=>{location.hash=target;});return;}dirty=false;if(!store&&!location.hash.startsWith('#view=')){try{store=P.storage(localStorage);state=store.get();}catch{say('수첩 저장소를 열지 못했어요.');return;}}render();});
window.addEventListener('storage',e=>{if(e.key===P.KEY)say('다른 창에서 수첩이 변경됐어요. 작성 중인 내용을 복사한 뒤 새로고침해 주세요.');});
try{if(location.hash.startsWith('#view=')){viewShare(location.hash.slice(6));}else{store=P.storage(localStorage);state=store.get();render();}}catch(e){say('저장소를 열지 못했습니다. 기존 기록을 덮어쓰지 않았어요.');app.innerHTML='<section class="pp-panel"><h2>기록 보호를 위해 수첩을 멈췄어요.</h2><p>브라우저의 사이트 저장 허용 여부를 확인해 주세요. 저장 내용이 손상된 경우 원본을 먼저 내려받아 보관할 수 있습니다.</p><button id="ppRecover">저장 원본 내려받기</button></section>';document.getElementById('ppRecover').onclick=()=>{try{const raw=localStorage.getItem(P.KEY);if(raw)download(new Blob([raw],{type:'text/plain'}),'seeya-passport-recovery.txt');else say('저장된 원본이 없습니다.');}catch{say('저장소에 접근할 수 없습니다. 브라우저 설정을 확인해 주세요.');}};}
if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.register('/passport/sw.js',{scope:'/passport/test/',updateViaCache:'none'}).then(reg=>{const report=()=>{document.getElementById('ppOffline').textContent=reg.active?'오프라인 수첩이 준비됐어요. 공개 일정은 마지막 저장본을 사용합니다.':'오프라인 수첩을 준비하고 있어요. 이 화면을 잠시 열어 두세요.';};report();if(reg.installing)reg.installing.addEventListener('statechange',report);reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',report));}).catch(()=>document.getElementById('ppOffline').textContent='오프라인 준비를 못 했어요. 연결된 상태에서 다시 열어 주세요.');}else document.getElementById('ppOffline').textContent='이 환경은 오프라인 수첩을 지원하지 않습니다.';
