'use strict';
const P=require('../shared/passport');
const attachPicker=require('./passport-picker');
const app=document.getElementById('passportApp'),status=document.getElementById('ppStatus');
const catalog=JSON.parse(document.getElementById('passportCatalog').textContent),E=P.esc;
let store,state,dirty=false,pendingImport=null,filterKind='',filterYear='',listMode=false,page=1,exportURL='',renderedHash=location.hash;
const say=s=>{status.textContent=s;};
const options=(items,selected)=>items.map(([v,t])=>`<option value="${E(v)}"${v===selected?' selected':''}>${E(t)}</option>`).join('');
const field=(label,name,value='',extra='')=>`<label class="pp-field"><span>${label}</span><input name="${name}" value="${E(value)}" ${extra}></label>`;
const memberNames=e=>e.members.map(m=>P.MEMBERS[m]).join(' · ')||'멤버 미지정';
const eventKind=e=>e?.type==='performance'?'concert':'story';
const kindState=e=>e.status==='planned'?'갈 예정':e.kind==='story'?'남긴 이야기':'다녀왔어요';
function save(next){try{state=store.save(next);dirty=false;return true;}catch(error){say(error.name==='QuotaExceededError'?'저장 공간이 부족합니다. 입력 내용을 복사해 두고 수첩을 백업해 주세요.':error.message||'저장하지 못했습니다. 입력 내용을 복사해 주세요.');return false;}}
function go(hash=''){dirty=false;if(location.hash===hash)render();else location.hash=hash;}
function linkBack(){return '<a class="pp-back" href="/passport/test/">← 내 수첩</a>';}
function profileCard(){const p=state.profile,n=P.summary(state.entries),years=p.since?Math.max(1,Number(P.today().slice(0,4))-Number(p.since.slice(0,4))+1):0;return `<section class="pp-panel pp-profile" style="--pp-color:${P.COLORS[p.color]}"><p class="pp-label">MY SEEYA · PERSONAL PASSPORT</p><div class="pp-name">${E(p.nickname||'나의 씨야 수첩')}</div><p class="pp-years">${years?'위듀 '+years+'년차':'우리의 첫 페이지'}</p><p class="pp-help">${p.since?'처음 좋아한 날 · '+P.dateLabel(p.since):'처음 좋아한 해부터 적어도 괜찮아요.'}</p>${p.motto?`<p class="pp-motto">${E(p.motto)}</p>`:''}<div class="pp-stats"><div><b>${n.concert}</b><span>공연 관람</span></div><div><b>${n.visit}</b><span>장소 방문</span></div><div><b>${n.event}</b><span>팬 행사</span></div><div><b>${n.story}</b><span>나의 이야기</span></div></div><a href="/passport/test/#profile">신분 카드 편집 →</a><p class="pp-help">나만의 경험을 모읍니다.<br>다른 사람과 비교하지 않아요.</p></section>`;}
function tour(){return `<section class="pp-panel"><p class="pp-label">THE FAN · 20TH ANNIVERSARY TOUR</p><h2>함께한 도시의 도장</h2><div class="pp-tour">${catalog.tour.map(t=>{const e=catalog.events.find(e=>e.id===t.eventId),records=state.entries.filter(x=>x.kind==='concert'&&(t.eventIds||[t.eventId]).includes(x.eventId)&&P.completed(x)),planned=state.entries.some(x=>(t.eventIds||[t.eventId]).includes(x.eventId)&&x.status==='planned');return `<button class="pp-stamp${records.length?' is-done':''}" data-event="${E(t.eventId)}" aria-label="${E(t.label)} 공연 기록하기"><strong><small>${t.dates?.length>1?t.dates.map(d=>d.slice(5).replace('-','.')).join(' · '):e?.date.slice(5).replace('-','.')||'미정'}</small>${E(t.label)}</strong><span>${records.length?'관람 '+records.length+'회':planned?'갈 예정':e?.date>P.today()?'다가오는 공연':'추억 남기기'}</span></button>`;}).join('')}</div><p class="pp-help">다녀온 공연만 도장이 찍혀요. 같은 도시를 여러 번 봤다면 회차별로 남겨주세요.</p></section>`;}
function home(){let rows=state.entries.filter(e=>(!filterKind||e.kind===filterKind)&&(!filterYear||e.date.slice(0,4)===filterYear)).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||b.createdAt.localeCompare(a.createdAt));const pages=Math.max(1,Math.ceil(rows.length/9));page=Math.min(page,pages);const years=[...new Set(state.entries.map(e=>e.date.slice(0,4)).filter(Boolean))].sort().reverse();app.innerHTML=`<div class="pp-layout">${profileCard()}<div>${tour()}<div class="pp-toolbar"><h2>내 기록 <small>${rows.length}</small></h2><button data-action="view" aria-pressed="${listMode}">${listMode?'스탬프 보기':'시간순 보기'}</button><div class="pp-filters"><select id="ppKindFilter" aria-label="기록 종류 필터">${options([['','모든 종류'],...Object.entries(P.KINDS)],filterKind)}</select><select id="ppYearFilter" aria-label="기록 연도 필터">${options([['','모든 연도'],...years.map(y=>[y,y+'년'])],filterYear)}</select></div></div>${rows.length?`<div class="pp-records${listMode?' is-list':''}">${rows.slice((page-1)*9,page*9).map(e=>`<a href="/passport/test/#entry=${encodeURIComponent(e.entryId)}" class="pp-record" data-kind="${e.kind}"><span class="pp-label">${P.KINDS[e.kind]}</span><h3>${E(e.title)}</h3><p>${P.dateLabel(e.date)}${e.time?' · '+e.time:''}</p><p>${E(e.snapshot.place||memberNames(e))}</p><span class="pp-state">${kindState(e)}</span></a>`).join('')}</div><div class="pp-pagination"><button data-page="${page-1}" ${page===1?'disabled':''}>이전</button><span>${page} / ${pages}</span><button data-page="${page+1}" ${page===pages?'disabled':''}>다음</button></div>`:`<div class="pp-empty"><strong>기억 하나로 시작해 보세요.</strong><p>첫 공연, 처음 씨야를 좋아했던 날.<br>날짜가 정확하지 않아도 괜찮아요.</p><a href="/passport/test/#new" class="pp-primary">＋ 첫 기록 남기기</a></div>`}</div></div>`;}
function ticket(e){return `<div class="pp-ticket"><p class="pp-label">WEDU PASSPORT · ${P.KINDS[e.kind]}</p><h2>${E(e.title)}</h2><p>${E(e.snapshot.place||'나의 기억 속 한 장면')}</p><div class="pp-ticket-cut"><p>${P.dateLabel(e.date)}${e.time?' · '+e.time:''}</p>${e.seat?`<p>좌석 · ${E(e.seat)}</p>`:''}<p>${E(memberNames(e))}</p><span class="pp-seal">${e.status==='planned'?'TO BE THERE':e.kind==='story'?'MY MEMORY':'I WAS HERE'}</span></div></div>`;}
function detail(id){const e=state.entries.find(e=>e.entryId===id);if(!e){app.innerHTML=linkBack()+'<p>기록을 찾지 못했어요. 백업 파일에서 복원할 수 있습니다.</p>';return;}const place=catalog.places.find(p=>p.id===e.placeId),event=catalog.events.find(x=>x.id===e.eventId);app.innerHTML=linkBack()+`<div class="pp-detail"><div>${ticket(e)}<div class="pp-actions" style="margin-top:18px"><button data-export="${E(id)}">티켓 이미지 저장</button><a href="/passport/test/#edit=${E(id)}">수정</a></div><p class="pp-help">공유 이미지에는 메모·동행인·좌석이 포함되지 않습니다.</p></div><section class="pp-panel"><h2>그날의 기억</h2><dl><dt>상태</dt><dd>${kindState(e)}</dd><dt>날짜</dt><dd>${P.dateLabel(e.date)}</dd><dt>함께</dt><dd>${E(e.companions||'기록하지 않았어요')}</dd><dt>정보 기준</dt><dd>${e.eventId?'일정에서 시작한 기록':e.placeId?'지도에서 시작한 기록':'직접 입력'}</dd></dl><p class="pp-note">${E(e.note||'아직 메모가 없어요.')}</p><div class="pp-actions">${place?`<a href="/map/?place=${encodeURIComponent(place.id)}">지도에서 보기</a>`:''}${event?.calendar?`<a href="/calendar/?month=${event.date.slice(0,7)}&event=${encodeURIComponent(event.id)}">연결된 일정</a>`:''}${e.archiveId&&catalog.events.some(x=>x.archiveId===e.archiveId)?`<a href="/archive/?record=${encodeURIComponent(e.archiveId)}">아카이브 기록</a>`:''}</div>${(e.eventId&&!event||e.placeId&&!place)?'<p class="pp-help">공개 정보의 연결이 사라졌지만 작성 당시 내용은 수첩에 남아 있어요.</p>':''}<div class="pp-danger"><button data-action="show-delete">이 기록 삭제</button><div id="ppDelete" class="pp-confirm" hidden><p>삭제 후에는 백업 파일이 있어야 복원할 수 있어요.</p><button data-delete="${E(id)}">이 기록을 삭제합니다</button></div></div></section></div><div id="ppExportResult"></div>`;}
function editor(existing,params=new URLSearchParams()){
 const ev=catalog.events.find(x=>x.id===params.get('event')),pl=catalog.places.find(x=>x.id===(params.get('place')||ev?.placeId));
 const now=new Date().toISOString(),e=existing||{entryId:crypto.randomUUID(),kind:ev?eventKind(ev):pl?'visit':'story',status:ev?P.defaultStatus(ev.date):pl?'planned':'done',title:ev?.title||pl?.name||'',date:ev?.date||'',time:ev?.time||'',members:ev?.members||[],eventId:ev?.id||'',placeId:pl?.id||'',archiveId:ev?.archiveId||'',snapshot:{title:ev?.title||'',place:pl?.name||ev?.venue||'',address:pl?.address||''},seat:'',companions:'',note:'',createdAt:now,updatedAt:now};
 const parts=e.date.split('-');app.innerHTML=linkBack()+`<section class="pp-panel"><h2>${existing?'기록 수정':'새 기록 남기기'}</h2><form id="ppEntryForm" class="pp-form-grid"><label class="pp-field"><span>기록 종류</span><select name="kind">${options(Object.entries(P.KINDS),e.kind)}</select></label><label class="pp-field"><span>기록 상태</span><select name="status">${options([['planned','갈 예정 / 계획'],['done','다녀왔어요 / 남긴 이야기']],e.status)}</select></label><div class="pp-wide pp-event-picker"><label class="pp-field" for="ppEventSearch"><span>등록된 일정 찾기 (선택)</span></label><input id="ppEventSearch" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="ppEventList" aria-describedby="ppEventHint" placeholder="공연명·장소·날짜 검색" autocomplete="off"><div id="ppEventList" class="pp-event-results" role="listbox" aria-label="검색된 일정" hidden></div><p id="ppEventHint" class="pp-help" role="status">검색 결과를 선택하면 제목·날짜·장소가 채워져요.</p><div id="ppSelectedEvent" class="pp-selected-event" hidden></div><div id="ppSessions" class="pp-sessions" role="group" aria-label="공연 날짜 선택" hidden></div></div><div class="pp-wide">${field('제목 *','title',e.title,'required maxlength="160"')}</div><div class="pp-wide"><span>날짜 (아는 만큼만)</span><div class="pp-date-fields">${field('연도','year',parts[0]||'','type="number" min="1900" max="2100" placeholder="미상"')}${field('월','month',parts[1]||'','type="number" min="1" max="12" placeholder="선택"')}${field('일','day',parts[2]||'','type="number" min="1" max="31" placeholder="선택"')}</div><p class="pp-help">날짜를 모두 비우면 ‘날짜 미상’으로 남아요.</p></div>${field('시간 (선택)','time',e.time,'type="time"')}${field('좌석 (선택)','seat',e.seat,'maxlength="100"')}${field('장소 이름 (직접 수정 가능)','place',e.snapshot.place,'maxlength="300"')}${field('함께 간 사람 (선택)','companions',e.companions,'maxlength="120"')}<fieldset class="pp-wide"><legend>함께한 멤버</legend><div class="pp-checks">${Object.entries(P.MEMBERS).map(([v,t])=>`<label><input type="checkbox" name="member" value="${v}"${e.members.includes(v)?' checked':''}>${t}</label>`).join('')}</div></fieldset><label class="pp-field pp-wide"><span>나만의 메모</span><textarea name="note" maxlength="4000" placeholder="그날의 마음을 적어 주세요.">${E(e.note)}</textarea></label><div class="pp-wide pp-draft-preview"><p class="pp-label">기록 미리보기</p><div id="ppDraft" class="pp-preview-summary"></div></div><div class="pp-wide pp-confirm" id="ppDuplicate" hidden><p>같은 날짜·회차의 비슷한 기록이 있어요.</p><label><input type="checkbox" name="allowDuplicate"> 별도의 경험으로 추가할게요</label></div><div class="pp-wide pp-actions"><button type="submit" class="pp-primary">${existing?'변경 내용 저장':'수첩에 기록하기'}</button><a href="/passport/test/">취소</a></div></form></section>`;
 const f=document.getElementById('ppEntryForm');let eventId=e.eventId,placeId=e.placeId,archiveId=e.archiveId,snapshot={...e.snapshot},statusManual=false;
 const preview=()=>{document.getElementById('ppDraft').textContent=[f.elements.title.value||'나의 기록',f.elements.place.value,[f.elements.year.value,f.elements.month.value,f.elements.day.value].filter(Boolean).join('.')||'날짜 미상',f.elements.status.value==='planned'?'갈 예정':f.elements.kind.value==='story'?'남긴 이야기':'다녀왔어요'].filter(Boolean).join(' · ');};preview();
 f.addEventListener('input',ev=>{dirty=true;if(ev.target.name==='allowDuplicate')return;document.getElementById('ppDuplicate').hidden=true;if(f.elements.allowDuplicate)f.elements.allowDuplicate.checked=false;preview();});
 f.elements.place.addEventListener('change',()=>{if(f.elements.place.value!==snapshot.place){placeId='';snapshot.address='';}});
 function selectedEvent(x){const box=document.getElementById('ppSelectedEvent'),sessions=document.getElementById('ppSessions');box.hidden=!x;box.innerHTML=x?`<div><small>연결된 일정</small><strong>${E(x.date+' · '+x.title)}</strong></div><button type="button" id="ppUnlinkEvent">연결 해제</button>`:'';const group=catalog.tour.find(t=>(t.eventIds||[t.eventId]).includes(x?.id));const choices=group?(group.eventIds||[group.eventId]).map(id=>catalog.events.find(x=>x.id===id)).filter(Boolean):[];sessions.hidden=choices.length<2;sessions.innerHTML=choices.length>1?'<p>공연 날짜를 선택해 주세요.</p><div>'+choices.map(v=>`<button type="button" data-session="${E(v.id)}" aria-pressed="${f.elements.year.value+'-'+String(f.elements.month.value).padStart(2,'0')+'-'+String(f.elements.day.value).padStart(2,'0')===v.date}">${E(P.dateLabel(v.date))}</button>`).join('')+'</div>':'';}
 function chooseEvent(x){dirty=true;statusManual=false;const p=catalog.places.find(p=>p.id===x.placeId);eventId=x.id;placeId=p?.id||'';archiveId=x.archiveId;snapshot={title:x.title,place:p?.name||x.venue,address:p?.address||''};for(const [k,v] of Object.entries({title:x.title,year:x.date.slice(0,4),month:Number(x.date.slice(5,7)),day:Number(x.date.slice(8,10)),time:x.time,place:snapshot.place,kind:eventKind(x),status:P.defaultStatus(x.date)}))f.elements[k].value=v;f.querySelectorAll('[name=member]').forEach(b=>b.checked=x.members.includes(b.value));document.getElementById('ppDuplicate').hidden=true;f.elements.allowDuplicate.checked=false;selectedEvent(x);preview();}
 selectedEvent(catalog.events.find(x=>x.id===eventId));
 attachPicker(document.getElementById('ppEventSearch'),document.getElementById('ppEventList'),document.getElementById('ppEventHint'),catalog.events,chooseEvent,E);
 f.addEventListener('click',ev=>{const b=ev.target.closest('button');if(b?.dataset.session){chooseEvent(catalog.events.find(x=>x.id===b.dataset.session));}else if(b?.id==='ppUnlinkEvent'){dirty=true;eventId='';archiveId='';selectedEvent(null);}});
 f.elements.status.addEventListener('change',()=>{statusManual=true;});
 for(const key of ['year','month','day'])f.elements[key].addEventListener('change',()=>{if(existing||statusManual)return;const y=f.elements.year.value,m=f.elements.month.value,d=f.elements.day.value,dt=y+(m?'-'+m.padStart(2,'0'):'')+(d?'-'+d.padStart(2,'0'):'');try{if(dt)f.elements.status.value=P.defaultStatus(P.date(dt));}catch{}preview();});
 f.addEventListener('submit',ev=>{ev.preventDefault();try{const y=f.elements.year.value,m=f.elements.month.value,d=f.elements.day.value;if((m&&!y)||(d&&(!y||!m)))throw Error('월·일을 입력하려면 앞의 연도·월도 입력해 주세요.');const dt=y+(m?'-'+m.padStart(2,'0'):'')+(d?'-'+d.padStart(2,'0'):'');const v=P.entry({...e,title:f.elements.title.value,kind:f.elements.kind.value,status:f.elements.status.value,date:dt,time:f.elements.time.value,seat:f.elements.seat.value,companions:f.elements.companions.value,note:f.elements.note.value,members:[...f.querySelectorAll('[name=member]:checked')].map(b=>b.value),eventId,placeId,archiveId,snapshot:{...snapshot,place:f.elements.place.value},updatedAt:new Date().toISOString()});if(v.status==='done'&&v.date>P.today().slice(0,v.date.length))throw Error('미래 날짜는 ‘갈 예정’으로 저장해 주세요.');if(state.entries.some(x=>x.entryId!==e.entryId&&P.duplicate(x,v))&&!f.elements.allowDuplicate.checked){document.getElementById('ppDuplicate').hidden=false;document.getElementById('ppDuplicate').scrollIntoView({block:'center'});return;}const entries=state.entries.filter(x=>x.entryId!==e.entryId).concat(v);if(save({...state,entries})){say('수첩에 저장했어요.');go('#entry='+v.entryId);}}catch(err){say(err.message);status.scrollIntoView({block:'center'});}});
}
function editProfile(){const p=state.profile;app.innerHTML=linkBack()+`<section class="pp-panel pp-settings"><h2>나의 신분 카드</h2><form id="ppProfile" class="pp-form-grid">${field('닉네임','nickname',p.nickname,'maxlength="30"')}${field('처음 좋아한 날','since',p.since,'placeholder="2006 또는 2006-03-12" maxlength="10"')}<p class="pp-help pp-wide">데뷔일인 2006년 3월 12일부터 오늘까지 입력할 수 있어요.<br>2006년·2006년 3월처럼 날짜를 모르면 해당 연도나 월까지만 적어도 괜찮아요.</p><label class="pp-field"><span>카드 색</span><select name="color">${options([['rose','로즈'],['violet','바이올렛'],['teal','그린'],['ink','잉크']],p.color)}</select></label>${field('응원 문구','motto',p.motto,'maxlength="120"')}<button class="pp-primary" type="submit">신분 카드 저장</button></form></section>`;const f=document.getElementById('ppProfile');f.addEventListener('input',()=>dirty=true);f.addEventListener('submit',e=>{e.preventDefault();try{const p=P.profile(Object.fromEntries(new FormData(f)));if(p.since>P.today().slice(0,p.since.length))throw Error('입덕일은 오늘 이전으로 입력해 주세요.');if(save({...state,profile:p})){say('신분 카드를 저장했어요.');go('');}}catch(e){say(e.message);}});}
function settings(){let last='';try{last=localStorage.getItem('seeya-passport-backup-date')||'';}catch{}app.innerHTML=linkBack()+`<div class="pp-settings"><section class="pp-panel"><h2>기록을 안전하게 가져가기</h2><p>현재 이 브라우저에 ${state.entries.length}개의 기록이 있어요. 다른 기기에서는 아래 백업 파일을 가져와 이어 쓸 수 있습니다.</p><button data-action="backup" class="pp-primary">백업 파일 내려받기</button><p class="pp-help">마지막 백업 요청: ${E(last||'아직 없어요')}<br>다운로드 후 파일이 실제로 저장됐는지 확인해 주세요.</p><a href="/about/install/">홈 화면에 추가하는 방법 →</a></section><section class="pp-panel"><h2>백업 가져오기</h2><p>내용을 먼저 확인한 다음 적용합니다. 잘못된 파일은 기존 기록을 바꾸지 않습니다.</p><input id="ppImport" type="file" accept="application/json,.json" aria-label="백업 JSON 파일 선택"><div id="ppImportPreview"></div></section><section class="pp-panel pp-danger"><h2>이 브라우저의 수첩 비우기</h2><p>신분 카드와 모든 개인 기록을 삭제합니다. 먼저 백업을 내려받아 주세요.</p><label class="pp-field"><span>계속하려면 ‘삭제’를 입력하세요.</span><input id="ppDeleteAllText" autocomplete="off"></label><button data-action="delete-all">전체 삭제</button></section></div>`;document.getElementById('ppImport').addEventListener('change',async ev=>{pendingImport=null;const preview=document.getElementById('ppImportPreview');preview.textContent='';const file=ev.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('8MB 이하의 백업 파일을 선택해 주세요.');const value=P.validate(JSON.parse(await file.text()));if(!preview.isConnected)return;const r=P.review(state,value);pendingImport=value;preview.innerHTML=`<div class="pp-confirm"><p>새 기록 ${r.added}건 · 같은 ID ${r.conflicts}건 · 중복 의심 ${r.suspected}건</p><p>가져올 신분 카드: ${E(value.profile.nickname||'이름 없음')}</p><label class="pp-field"><span>같은 ID 처리</span><select id="ppImportMode"><option value="keep">현재 기록 유지</option><option value="replace">가져온 기록으로 교체</option></select></label><label><input id="ppImportProfile" type="checkbox"> 신분 카드도 가져오기</label><p class="pp-help">다른 ID의 중복 의심 기록은 합치지 않습니다. 적용 전 백업을 권장합니다.</p><button data-action="apply-import" class="pp-primary">확인한 내용 가져오기</button></div>`;}catch(e){say('가져오지 않았습니다. '+(e instanceof SyntaxError?'JSON 백업 파일을 확인해 주세요.':e.message));}});}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function backup(){download(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),`seeya-passport-${P.today()}-${state.entries.length}entries.json`);try{localStorage.setItem('seeya-passport-backup-date',P.today());}catch{}say('백업 다운로드를 요청했어요. 파일 저장을 확인해 주세요.');}
async function exportTicket(e){try{const c=document.createElement('canvas');c.width=1080;c.height=1350;const g=c.getContext('2d');if(!g)throw Error('이미지 생성을 지원하지 않는 브라우저입니다.');g.fillStyle='#fcf8f5';g.fillRect(0,0,1080,1350);g.fillStyle='#29242d';g.fillRect(70,70,940,1210);g.fillStyle='#edb4cc';g.font='22px sans-serif';g.fillText('SEEYA ARCHIVE · WEDU PASSPORT',125,155);g.fillStyle='#fff';
 const wrap=(txt,y,font,line,max)=>{g.font=font;let lines=[''];for(const ch of txt){const i=lines.length-1;if(g.measureText(lines[i]+ch).width>810)lines.push(ch);else lines[i]+=ch;}lines=lines.slice(0,max);for(const s of lines){g.fillText(s,125,y);y+=line;}return y;};
 wrap(e.title,290,'bold 54px sans-serif',80,4);wrap(e.snapshot.place||P.KINDS[e.kind],650,'30px sans-serif',46,3);g.strokeStyle='#c58bA3';g.setLineDash([12,12]);g.beginPath();g.moveTo(70,860);g.lineTo(1010,860);g.stroke();g.font='34px sans-serif';g.fillText(P.dateLabel(e.date)+(e.time?' · '+e.time:''),125,945);wrap(memberNames(e),1020,'28px sans-serif',44,2);g.fillStyle='#edb4cc';g.font='bold 30px sans-serif';g.fillText(kindState(e),125,1170);g.font='20px sans-serif';g.fillText('나의 기억으로 남긴 기록 · 공식 입장권이 아닙니다',125,1220);const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('이미지를 만들지 못했어요.')),'image/png'));if(exportURL)URL.revokeObjectURL(exportURL);exportURL=URL.createObjectURL(blob);document.getElementById('ppExportResult').innerHTML=`<section class="pp-panel"><h2>티켓 이미지</h2><img class="pp-export" src="${exportURL}" alt="내 공연 기록 티켓 미리보기"><div class="pp-actions"><a href="${exportURL}" download="seeya-ticket.png">PNG 내려받기</a><button id="ppShareImage">이미지 공유</button></div><p class="pp-help">사진 앱에서 배경화면으로 설정하거나 SNS에 직접 올릴 수 있어요.</p></section>`;document.getElementById('ppShareImage').onclick=async()=>{const file=new File([blob],'seeya-ticket.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});}catch(err){if(err.name!=='AbortError')say('공유를 열지 못했어요. PNG 내려받기를 이용해 주세요.');}}else download(blob,'seeya-ticket.png');};document.getElementById('ppExportResult').scrollIntoView({block:'start'});}catch(err){say(err.message);}}
function render(){if(P.beforeDebut(state.profile.since))say('기존 입덕일이 데뷔일 이전이에요. 신분 카드에서 날짜를 수정해 주세요. 기존 기록은 그대로 보관했습니다.');renderedHash=location.hash;if(exportURL){URL.revokeObjectURL(exportURL);exportURL='';}pendingImport=null;const h=location.hash.slice(1);if(h==='settings')settings();else if(h==='profile')editProfile();else if(h==='new'||h.startsWith('new?'))editor(null,new URLSearchParams(h.split('?')[1]||''));else if(h.startsWith('edit=')){const e=state.entries.find(x=>x.entryId===h.slice(5));if(e)editor(e);else detail(h.slice(5));}else if(h.startsWith('entry='))detail(h.slice(6));else home();}
app.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b||!store)return;if(b.dataset.event){go('#new?event='+encodeURIComponent(b.dataset.event));return;}if(b.dataset.page){page=Number(b.dataset.page);home();return;}if(b.dataset.export){exportTicket(state.entries.find(x=>x.entryId===b.dataset.export));return;}if(b.dataset.delete){if(save({...state,entries:state.entries.filter(x=>x.entryId!==b.dataset.delete)})){say('기록을 삭제했어요.');go('');}return;}switch(b.dataset.action){case 'view':listMode=!listMode;home();break;case 'show-delete':document.getElementById('ppDelete').hidden=false;break;case 'backup':backup();break;case 'delete-all':if(document.getElementById('ppDeleteAllText').value!=='삭제'){say('확인란에 ‘삭제’를 입력해 주세요.');break;}if(save(P.empty())){say('이 브라우저의 개인 수첩을 비웠어요.');go('');}break;case 'apply-import':if(pendingImport){try{const next=P.merge(state,pendingImport,document.getElementById('ppImportMode').value==='replace',document.getElementById('ppImportProfile').checked);if(save(next)){say('백업을 가져왔어요.');go('');}}catch(e){say(e.message);}}break;}});
app.addEventListener('change',e=>{if(e.target.id==='ppKindFilter'){filterKind=e.target.value;page=1;home();}if(e.target.id==='ppYearFilter'){filterYear=e.target.value;page=1;home();}});
function confirmDiscard(leave){
 if(document.getElementById('ppDiscard'))return;
 const panel=document.createElement('div');panel.id='ppDiscard';panel.className='pp-discard';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','ppDiscardTitle');
 panel.innerHTML='<div class="pp-panel"><h2 id="ppDiscardTitle">아직 저장하지 않은 입력이 있어요.</h2><p>이동하면 지금 작성 중인 내용은 사라집니다.</p><div class="pp-actions"><button id="ppStay">계속 작성</button><button id="ppLeave">저장하지 않고 이동</button></div></div>';
 const prior=document.activeElement;document.querySelector('.passport-page').append(panel);
 const stay=panel.querySelector('#ppStay'),exit=panel.querySelector('#ppLeave');stay.focus();
 stay.onclick=()=>{panel.remove();prior?.focus();};exit.onclick=()=>{panel.remove();dirty=false;leave();};
 panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();stay.click();}if(e.key==='Tab'){e.preventDefault();(document.activeElement===stay?exit:stay).focus();}});
}
document.addEventListener('click',e=>{if(!dirty)return;const a=e.target.closest('a');if(a){e.preventDefault();confirmDiscard(()=>location.href=a.href);}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>{if(dirty){const target=location.hash;history.replaceState(null,'',location.pathname+location.search+renderedHash);confirmDiscard(()=>{location.hash=target;});return;}dirty=false;render();});
window.addEventListener('storage',e=>{if(e.key===P.KEY)say('다른 창에서 수첩이 변경됐어요. 작성 중인 내용을 복사한 뒤 새로고침해 주세요.');});
try{store=P.storage(localStorage);state=store.get();render();}catch(e){say('저장소를 열지 못했습니다. 기존 기록을 덮어쓰지 않았어요.');app.innerHTML='<section class="pp-panel"><h2>기록 보호를 위해 수첩을 멈췄어요.</h2><p>브라우저의 사이트 저장 허용 여부를 확인해 주세요. 저장 내용이 손상된 경우 원본을 먼저 내려받아 보관할 수 있습니다.</p><button id="ppRecover">저장 원본 내려받기</button></section>';document.getElementById('ppRecover').onclick=()=>{try{const raw=localStorage.getItem(P.KEY);if(raw)download(new Blob([raw],{type:'text/plain'}),'seeya-passport-recovery.txt');else say('저장된 원본이 없습니다.');}catch{say('저장소에 접근할 수 없습니다. 브라우저 설정을 확인해 주세요.');}};}
if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.register('/passport/sw.js',{scope:'/passport/test/',updateViaCache:'none'}).then(reg=>{const report=()=>{document.getElementById('ppOffline').textContent=reg.active?'오프라인 수첩이 준비됐어요. 공개 일정은 마지막 저장본을 사용합니다.':'오프라인 수첩을 준비하고 있어요. 이 화면을 잠시 열어 두세요.';};report();if(reg.installing)reg.installing.addEventListener('statechange',report);reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',report));}).catch(()=>document.getElementById('ppOffline').textContent='오프라인 준비를 못 했어요. 연결된 상태에서 다시 열어 주세요.');}else document.getElementById('ppOffline').textContent='이 환경은 오프라인 수첩을 지원하지 않습니다.';
